USE DEPO
SELECT MODEL_ID,TIP FROM PRODUSE
	WHERE CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1))%2!=0 AND
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1))%2=0 AND 
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1)) < CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1)) AND 
	(CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1)) * CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1))) AS PRODUS -- IMI DA EROARE