USE ANGAJAT

SELECT NUME,PRENUME,
	IIF(MONTH(GETDATE())>=MONTH(DATA_NASTERII),YEAR(GETDATE())-YEAR(DATA_NASTERII),YEAR(GETDATE())-YEAR(DATA_NASTERII)-1) AS ANI,
	IIF(MONTH(GETDATE())>=MONTH(DATA_NASTERII),MONTH(GETDATE())-MONTH(DATA_NASTERII),11-MONTH(DATA_NASTERII)+MONTH(GETDATE))) AS LUNI,
	IIF(DAY(GETDATE())>=DAY(DATA_NASTERII),DAY(GETDATE())-DAY(DATA_NASTERII),DAY(DATEADD(DAY,-1,DATEADD(MONTH,1,DATEADD(DAY,-1,DAY(DATA_NASTERII))))))
	FROM ANGAJAT

SELECT DATEADD(DAY,1-DAY(DATA_NASTERII),DATA_NASTERII),
	   DATEADD(MONTH,1,DATEADD(DAY,1-DAY(DATA_NASTERII),DATA_NASTERII)),
	   DATEADD(DAY,-1,DATEADD(MONTH,1,DATEADD(DAY,1-DAY(DATA_NASTERII),DATA_NASTERII))),
	   GETDATE()-1
	   FROM ANGAJAT


--SINTAXA DATEADD
--DATEADD(ZI,LUNA,ANI(DUPA DORINTA),10,DATA_NASTERII)
--10 - CATE ZILE DORIM
--DATA_NASTERII - CE DORIM SA MARIM

--FUNCTII DEFINITE DE UTILIZATOR
--FUNCTIILE DEFINITE SUNT DE 2 TIPURI:
--	1. FUNCTIA SCALARA - FUNCTIA RETURNEAZA UN SINGUR RASPUNS (DDL)
--	2. FUNCTIA TABELERA - FUNCTIA RETURNEAZA O TABELA VIRTUALA

--FUNCTIA SCALARA (SINTAXA):
CREATE FUNCTION NUME_FUNCTIE([LISTA_PARAMETRILOR_EFECTIVI])
	RETURNS TIP_DATE
	BEGIN
		INSTRUCTIUNI;
		RETURN REZULTAT
	END;

--APELUL FUNCTIEI - SE FACE PRIN SELECT SAU PRINT
--SELECT DBO.NUME_FUNCTIE([LISTA_PARAMETRILOR_REALI])

--TRANSACT SQL
--DECLARAREA UNEI VARIABILE
--@NUME_VARIABILA TIP_DATE; - PENTRU A INITIAZA O VARIABILA VOM UTILIZA SET
--	SET @NUME_VARIABILA=2; - SE UTILIZEAZA IN AFARA SELECTULUI
--	INTO - SE UTILIZEAZA IN INTERIORUL SELECTULUI

ALTER FUNCTION SUMA(@A INT,@B INT,@C INT)
	RETURNS INT
	BEGIN
		DECLARE @D INT
		IF @A<0 SET @A=0
		IF @B<0 SET @B=0
		IF @C<0 SET @C=0
		SET @D=@A+@B+@C
		RETURN @D
	END

SELECT DBO.SUMA(23,21,-13) AS SUMAA
PRINT DBO.SUMA(23,21,-13)

SELECT *,
	IIF(DATA_ELIBERARII IS NULL,DBO.SUMA(SALARIU,BONUS_SALARIU,-PENALITATI_SALARIU),0) AS SAL_TOTAL FROM ANGAJARE

SELECT * FROM ANGAJAT A INNER JOIN ANGAJARE AA
	ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	WHERE SALARIU=
	(
		SELECT MIN(SALARIU) FROM ANGAJARE
	)

CREATE FUNCTION MIN_SAL()
	RETURNS NUMERIC(11,2)
	BEGIN
		RETURN (SELECT MIN(SALARIU) FROM ANGAJARE)
	END

SELECT * FROM ANGAJAT A INNER JOIN ANGAJARE AA
	ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	WHERE SALARIU=DBO.MIN_SAL()

--SA SE CALCULEZE PENTRU FIECARE DEPARTAMENT NUMARUL DE PERSOANE
SELECT *,
	(
		SELECT COUNT(DISTINCT(ANGAJAT_ID)) FROM ANGAJARE A
		WHERE A.DEPARTAMENT_ID=D.DEPARTAMENT_ID
	) AS NR
	FROM DEPARTAMENT D

CREATE FUNCTION NR_PERS_DEP(@ID_DEP INT)
	RETURNS INT
	BEGIN
		RETURN
		(
			SELECT COUNT(DISTINCT(ANGAJAT_ID)) FROM ANGAJARE A
			WHERE A.DEPARTAMENT_ID=@ID_DEP
		)
	END

SELECT *,DBO.NR_PERS_DEP(D.DEPARTAMENT_ID) AS NR
	FROM DEPARTAMENT D

--tema pe data trecuta o facem in functie
