--1. CAND UTILIZAM NUMAI FUNCTII DE GRUP
SELECT COUNT(*) AS NR, MAX(PRET) AS MAXIM, AVG(PRET) AS MEDIA FROM PC
--2. CAND SE UTILIZEAZA COMBINATIE: FUNCTIE DE GRUP SI FUNCTIE DE RAND
SELECT PRODUCATOR,
	COUNT(*) AS NR_PRODUCATOR
	FROM PRODUSE
	GROUP BY PRODUCATOR
	ORDER BY NR_PRODUCATOR

SELECT * 
	FROM PRODUSE
	ORDER BY PRODUCATOR,TIP

SELECT *
	FROM PC
	ORDER BY PRET,HDD

SELECT PRODUCATOR,
	COUNT(DISTINCT(TIP)) AS NR_PRODUCATOR
	FROM PRODUSE
	GROUP BY PRODUCATOR
	ORDER BY NR_PRODUCATOR

--STUDIUL LIKE - CAUTATREA DUPA UN SIR DE CARACTERE
--1:
SELECT * FROM PRODUSE WHERE TIP LIKE 'PC' --TIP='PC'
--2:
SELECT * 
	FROM PRODUSE
	WHERE TIP LIKE '%E'
--3:
SELECT *
	FROM PRODUSE
	WHERE TIP LIKE 'I%'
--4:
SELECT *
	FROM PRODUSE
	WHERE TIP LIKE '%PR%'

SELECT * FROM PC
SELECT MODEL_ID AS MODEL,
	VITEZA,
	HDD AS HD
	FROM PC
	WHERE PRET<4000
	
--SA SE GASEASCA PRODUCATORII DE IMPRIMANTE
SELECT PRODUCATOR
	FROM PRODUSE
	WHERE TIP='IMRPRIMANTE'
	GROUP BY PRODUCATOR
--SA SE GASEASCA MODELUL CAPACITATEA DE MEMORIE OPERATIVA SI DIMENSIUNEA 
--ECRANULUI FIECARUI LAPTOP CU UN PRET MAI MARE DE 8 MII DE LEI
SELECT * FROM LAPTOPURI
SELECT MODEL_ID,VITEZA,ECRAN
	FROM LAPTOPURI
	WHERE PRET>8000
--SA SE GASEASCA TOATE IMPRIMANTELE COLOR. ARANJATI INFO DUPA PRET
--IN FORMA DESC
SELECT *
	FROM IMPRIMANTE
	WHERE COLOR='DA'
	ORDER BY PRET DESC
--SA SE GASEASCA MODELUL VITEZA PROCESURULUI SI CAPACITATEA DISCULUI DUR
--ALE PC-URILOR MAI IEFTINE DE 6000 LEI CE POSEDA CD-ROOM CU VITEZE
--12X SAU 24X
SELECT MODEL_ID,VITEZA,HDD
	FROM PC
	WHERE PRET<6000 AND CD IN('12X','24X')
--PENTRU FIECARE PC CU ACELASI RAM SA SE CALCULEZE MEDIA ARITMETICA
--DUPA PRET
SELECT * FROM PC
SELECT RAM,
	COUNT(*) AS NR,
	AVG(PRET) AS MEDIE
	FROM PC GROUP BY RAM HAVING COUNT(*)>1
--SA SE GASEASCA PRODUCATORII CARE VAND IMPRIMANTE SAU LAPTORURI, DAR NU VAND PC-URI !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SELECT * FROM PRODUSE
SELECT PRODUCATOR
	FROM PRODUSE
	WHERE TIP IN('IMRPIMANTE','LAPTOP')
	GROUP BY PRODUCATOR
--SA SE GASEASCA PC-URILE CU PROCESOARE CE FUNCTIONEAZA CU FRECVENTA DE TACT
--NUMAI 1500 DE MHZ. AFISATI MODEL VITEZA SI -20% DIN VALOAREA PRETULUI
SELECT * FROM PC 
SELECT MODEL_ID AS MODEL,VITEZA,PRET-(PRET*0.2) AS REDUCERE
	FROM PC
--SA SE GASEASCA VITEZA MEDIE A LAPTOPURILOR CU ECRAN CUPRINS INTRE 12 SI
--15 INCH

SELECT * FROM LAPTOPURI
SELECT MODEL_ID,
	CONVERT(DECIMAL(9,2),AVG(VITEZA)) AS MEDIA_V
	FROM LAPTOPURI
	WHERE ECRAN BETWEEN 12 AND 15
	GROUP BY MODEL_ID
--SA SE GASEASCA TOATE PC-URILE LA CARE AL DOILEA SIMBOL DIN PRET
--ESTE O CIFRA PARA
SELECT * FROM PC
	WHERE CONVERT(INT,SUBSTRING(CONVERT(VARCHAR(8),PRET),2,1))%2=0

--SA SE GASEASCA MODELE DIN TABELA PRODUSE LA CARE PRIMA CIFRA DIN MODEL
--ESTE O CIFRA IMPARA, IAR ULTIMA PARA SI PRIMA CIFRA MAI MIC DECAT ULTIMA
--SA SE AFISEZE MODELUL, TIPUL PRODUSULUI, PRECUM SI PRODUSUL DINTRE PRIMA
--SI ULTIMA CIFRA A MODELULUI
USE DEP()
SELECT MODEL_ID,TIP FROM PRODUSE
	WHERE CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1))%2!=0 AND
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1))%2=0 AND 
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1)) < CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1)) AND 
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1)) * CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1)) 
	
	