USE DEPO

SELECT COUNT(*) AS NR,MAX(PRET) AS MAXIM,AVG(PRET) AS MEDIA
	FROM PC

SELECT PRODUCATOR,COUNT(*) AS NR_PRODUCATOR
	FROM PRODUSE
	GROUP BY PRODUCATOR
	ORDER BY NR_PRODUCATOR

SELECT *
	FROM PRODUSE
	ORDER BY PRODUCATOR,TIP

SELECT *
	FROM PC
	ORDER BY PRET,HDD

SELECT PRODUCATOR,COUNT(DISTINCT(TIP)) AS NR_PRODUCATOR
	FROM PRODUSE
	GROUP BY PRODUCATOR
	ORDER BY NR_PRODUCATOR

SELECT *
	FROM PRODUSE
	WHERE TIP LIKE 'PC'

SELECT *
	FROM PRODUSE
	WHERE TIP LIKE '%E'

SELECT *
	FROM PRODUSE
	WHERE TIP LIKE 'I%'

SELECT *
	FROM PRODUSE
	WHERE TIP LIKE '%PR%'

SELECT MOLDE_ID AS MODEL,VITEZA,HDD AS HD
	FROM PC
	WHERE PRET<4000

SELECT PRODUCATOR
	FROM PRODUSE
	WHERE TIP='IMPRIMANTE'
	GROUP BY PRODUCATOR

SELECT MODEL_ID,VITEZA,ECRAN
	FROM LAPTOPURI
	WHERE PRET>8000

SELECT *
	FROM IMPRIMANTE
	WHERE COLOR='DA'
	ORDER BY PRET DESC

SELECT MODEL_ID,VITEZA,HDD
	FROM PC
	WHERE PRET<6000 AND CD IN('12X','24X')

SELECT PRODUCATOR
	FROM PRODUSE
	WHERE TIP IN('IMPRIMANTE','LAPTOP')
	GROUP BY PRODUCATOR

SELECT MODEL_ID AS MODEL,VITEZA,PRET-(PRET*0.2) AS REDUCERE
	FROM PC

SELECT MODEL_ID,CONVERT(DECIMAL(9,2),AVG(VITEZA)) AS MEDIA_V
	FROM LAPTOPURI
	WHERE ECRAN BETWEEN 12 AND 15
	GROUP BY MODEL_ID

SELECT *
	FROM PC
	WHERE CONVERT(INT,SUBSTRING(CONVERT(VARCHAR(8),PRET),2,1))%2=0

SELECT MODEL_ID,TIP 
	FROM PRODUSE
	WHERE CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1))%2!=0 AND
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1))%2=0 AND
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1))<CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1)) AND
	CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),1,1))*CONVERT(INT,SUBSTRING(CONVERT(VARCHAR,MODEL_ID),4,1)) 