CREATE TABLE PERSOANE
(
PERSOANE_ID INT PRIMARY KEY IDENTITY(1,1),
NUME VARCHAR(20) NOT NULL,
PRENUME VARCHAR(20) NOT NULL,
DATA_N DATE,
GEN CHAR(1),
IDNP VARCHAR(13) NOT NULL
)

CREATE TABLE SERIA
(
SERIA_ID INT PRIMARY KEY IDENTITY(1,1),
NUME VARCHAR(3)
)

CREATE TABLE INSTITUTIA
(
INSTITUATIA_ID INT PRIMARY KEY IDENTITY(1,1),
NUME VARCHAR(50)
)

CREATE TABLE TIP
(
TIP_ID INT PRIMARY KEY IDENTITY(1,1),
NUME VARCHAR(50)
)

CREATE TABLE DIPLOME
(
DIPLOMA_ID INT PRIMARY KEY IDENTITY(1,1),
PERSOANE_ID INT FOREIGN KEY REFERENCES PERSOANE(PERSOANE_ID),
SERIA_ID INT FOREIGN KEY REFERENCES SERIA(SERIA_ID),
INSTITUTIA_ID INT FOREIGN KEY REFERENCES INSTITUTIA(INSTITUATIA_ID),
TIP_ID INT FOREIGN KEY REFERENCES TIP(TIP_ID),
NR_DIPLOMA VARCHAR(18) NOT NULL
)