USE FACTURI

CREATE TABLE CLIENT (
	CLIENT_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20) NOT NULL,
	PRENUME VARCHAR(20) NOT NULL
)

CREATE TABLE PRODUS (
	PRODUS_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(50),
	PRET INT
)

CREATE TABLE LUNA (
	LUNA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20)
)

CREATE TABLE BANCA (
	BANCA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20)
)

CREATE TABLE DELEGAT (
	DELEGAT_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20),
	PRENUME VARCHAR(20)
)

CREATE TABLE FACTURI (
	FACTURI_ID INT PRIMARY KEY IDENTITY(1,1),
	ZI_FACTURA INT,
	LUNA_ID INT FOREIGN KEY REFERENCES LUNA(LUNA_ID),
	CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
	ADRESA_CLIENT VARCHAR(30),
	BANCA_ID INT FOREIGN KEY REFERENCES BANCA(BANCA_ID),
	NR_CONT_CLIENT INT NOT NULL,
	DELEGAT_ID INT FOREIGN KEY REFERENCES DELEGAT(DELEGAT_ID),
	PRODUS_ID INT FOREIGN KEY REFERENCES PRODUS(PRODUS_ID),
	VALOARE_TVA INT NOT NULL,
	TOTAL_VALOARE_FACTURA INT NOT NULL,
	TOTAL_VALOARE_TVA INT NOT NULL

)