CREATE FUNCTION F1(@X INT)
	RETURNS INT
	BEGIN
		DECLARE @Y INT;
		SET @Y=0;
		WHILE @X<=5
			BEGIN
				SET @Y=@Y+@X;
				SET @X=@X+1;
			END
		RETURN @Y;
	END;

SELECT DBO.F1(2)

--PENTRU O ANUMITA PERSOANA CE ARE MAI MULTE ANGAJARI SA SE INDICE LISTA FUNCTIILOR IN CARE ESTE ANGAJAT
--REZULTATUL SA AIBA URM FORMA: NUME,LISTA FUNCTIILOR

CREATE FUNCTION ANGAJARI(@ANG INT)
	RETURNS VARCHAR(250)
	BEGIN
		DECLARE @NR INT;
		DECLARE @REZ VARCHAR(250);
		SET @NR=
		(
			SELECT COUNT(*) 
				FROM ANGAJARE WHERE ANGAJAT_ID=@ANG
				AND DATA_ELIBARARII IS NULL
		);
		WHILE 
			BEGIN

			END
		RETURN @REZ;
	END;


--DECLANSATOARE (TRIGERI)
--SINTAXA:
--CREATE TRIGGER NUME_TRIGGER ON NUME_TABELA 
--	AFTER INSERT/UPDATE/DELETE
--	AS INSTRUCTIUNI

--SA SE SCRIE UN TRIGGER CARE SA REACTIONEZE LA INREGISTRAREA UNEI INFO IN TABELA

ALTER TRIGGER INREGISTRARE ON PRODUSE 
	AFTER INSERT,UPDATE
	AS PRINT 'INREGISTRARE CU SUCCES';

INSERT INTO PRODUSE(PRODUCATOR,TIP)
	VALUES('X','BOX')

UPDATE PRODUSE SET PRODUCATOR='X' WHERE PRODUCATOR='Y'

ALTER TRIGGER VERIF ON PRODUSE
	AFTER DELETE
	AS
	DECLARE @NR INT;
	SET @NR=
	(
		SELECT COUNT(*) FROM PRODUSE WHERE PRODUCATOR='X'
	);
	IF(@NR=0)
		BEGIN
			PRINT 'TRANZACTIE ANULATA';
			ROLLBACK TRANSACTION;
		END;

DELETE PRODUSE WHERE MODEL_ID=2113
COMMIT - FARA POSIBILITATEA DE A TE REINTOARCE

--SA SE SCRIE UN TRIGGER ASUPRA TABELEI PC CARE SA REACTIONEZE IN MOMENTUL IN CARE 
--SE MODIFICA PRETUL
CREATE TRIGGER VERIF_PRET ON PC
	AFTER UPDATE
	AS
	DECLARE @PRET_NOU FLOAT;
	DECLARE @PRET_VECHI FLOAT;
	IF UPDATE(PRET)
		BEGIN
			SET @PRET_NOU=
			(
				SELECT PRET FROM INSERTED
			);
			SET @PRET_VECHI=
			(
				SELECT PRET FROM DELETED
			);
			PRINT 'S-A MODIFICAT PRETUL DIN '+CAST(@PRET_VECHI AS VARCHAR(20))+' LEI IN '+CAST(@PRET_NOU AS VARCHAR(20))+' LEI';
		END;

UPDATE PC SET PRET=9200 WHERE PC_ID=25

SELECT * FROM PC

CREATE TABLE LOGG
(
	LOGG_ID INT PRIMARY KEY IDENTITY(1,1),
	MODEL_ID INT,
	PRODUCATOR CHAR,
	TIP VARCHAR(15),
	DATE_EXEC DATE DEFAULT GETDATE(),
	ORA_EXEC TIME DEFAULT GETDATE(),
	UTILIZATOR VARCHAR(20) 
)

CREATE TRIGGER LG ON PRODUSE
	AFTER UPDATE
	AS 
	DECLARE @MMODEL_ID INT;
	DECLARE @PPRODUCATOR CHAR;
	DECLARE @TIP VARCHAR(20);
	SET @MMODEL_ID=
	(
		SELECT MODEL_ID FROM DELETED
	);
	SET @PPRODUCATOR=
	(
		SELECT PRODUCATOR FROM DELETED
	);
	SET @TIP=
	(
		SELECT TIP FROM DELETED
	);
	INSERT INTO LOGG(MODEL_ID,PRODUCATOR,TIP,UTILIZATOR)
		VALUES(@MMODEL_ID,@PPRODUCATOR,@TIP,USER_NAME())

UPDATE PRODUSE SET TIP='BOX' WHERE MODEL_ID=2113