ALTER TRIGGER B_SALAR_MODIF ON ANGAJARE
	AFTER UPDATE
	AS
	DECLARE @SALAR_NOU DECIMAL(10,1)
	IF UPDATE(BONUS_SALARIU)
	BEGIN
		SET @SALAR_NOU=
		(
			SELECT TOP 1 BONUS_SALARIU FROM inserted
		);
		IF(@SALAR_NOU>20000)
		BEGIN
			UPDATE ANGAJARE SET PENALITATI_SALARIU=(0.2*BONUS_SALARIU)
			WHERE ANGAJARE_ID IN 
			(
				SELECT ANGAJARE_ID FROM inserted
			)
		END
	END;


BEGIN TRANSACTION
UPDATE ANGAJARE SET BONUS_SALARIU=35900 
	WHERE ANGAJARE_ID IN(8,9)
	ROLLBACK TRANSACTION
	END;

BEGIN TRANSACTION
UPDATE ANGAJARE SET BONUS_SALARIU=10 
	WHERE ANGAJARE_ID=13
	ROLLBACK TRANSACTION
