USE ANGAJAT

SELECT MONTH(DATA_ANGAJARII) AS LUNA,SUM(SALARIU) AS SUMA
	FROM ANGAJARE
	GROUP BY MONTH(DATA_ANGAJARII)

SELECT YEAR(DATA_ANGAJARII) AS ZI,SUM(SALARIU) AS SUMA
	FROM ANGAJARE
	GROUP BY YEAR(DATA_ANGAJARII)

SELECT MONTH(DATA_NASTERII),COUNT(*)
	FROM ANGAJAT
	GROUP BY MONTH(DATA_NASTERII)