USE DEPO

SELECT PRET,MODEL_ID,
(
	CASE
	WHEN PRET<5000 THEN 'ECONOM'
	WHEN PRET BETWEEN 5000 AND 8000 THEN 'BUSINESS'
	ELSE 'PREMIUM'
	END
) AS PRICE
	FROM LAPTOPURI

SELECT PRET,MODEL_ID,
	IIF(PRET<5000,'ECONOM',IIF(PRET BETWEEN 5000 AND 8000,'BUSINESS','PREMIUM')) AS PRICE
	FROM LAPTOPURI

SELECT PRODUCATOR,
(
	SELECT IIF(COUNT(*)>0,'DA','NU') FROM LAPTOPURI L INNER JOIN PRODUSE P ON L.MODEL_ID=P.MODEL_ID
	WHERE PP.PRODUCATOR=P.PRODUCATOR
) AS TYPE_LAPTOPURI,
(
	SELECT IIF(COUNT(*)>0,'DA','NU') FROM PC INNER JOIN PRODUSE P ON PC.MODEL_ID=P.MODEL_ID
	WHERE PP.PRODUCATOR=P.PRODUCATOR
) AS TYPE_PC,
(
	SELECT IIF(COUNT(*)>0,'DA','NU') FROM IMPRIMANTE I INNER JOIN PRODUSE P ON I.MODEL_ID=P.MODEL_ID
	WHERE PP.PRODUCATOR=P.PRODUCATOR
) AS TYPE_IMPRIMANTE
	FROM PRODUSE PP
	GROUP BY PRODUCATOR

USE ANGAJAT

SELECT NUME+' '+PRENUME AS NUME,SALARIU
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	INNER JOIN LOC_STR LS ON LS.LOC_STR_ID=A.LOC_STR_ID
	INNER JOIN LOCALITATE L ON L.LOCALITATE_ID=LS.LOCALITATE_ID
	WHERE DATA_ELIBARARII IS NULL AND LOCALITATE LIKE '%CHI%'
	AND SALARIU>(SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL)

SELECT NUME+' '+PRENUME AS ANGAJAT,SUM(SALARIU) AS SALARIU
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	WHERE DATA_ELIBARARII IS NULL
	AND SALARIU>
	(
		SELECT AVG(SALARIU) FROM ANGAJARE AA INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=AA.DEPARTAMENT_ID
		WHERE DENUMIRE='IT'
	)
	GROUP BY NUME+' '+PRENUME 

SELECT *
	FROM
	(
		SELECT DENUMIRE_FUNCTIE,COUNT(*) AS NR
		FROM FUNCTIE F INNER JOIN ANGAJARE AA ON AA.FUNCTIE_ID=F.FUNCTIE_ID
		GROUP BY DENUMIRE_FUNCTIE
	) AS X
	WHERE NR=
	(
		SELECT MAX(NR) FROM
		(
			SELECT DENUMIRE_FUNCTIE,COUNT(*) AS NR
			FROM FUNCTIE F INNER JOIN ANGAJARE AA ON AA.FUNCTIE_ID=F.FUNCTIE_ID
			GROUP BY DENUMIRE_FUNCTIE
		) AS Y
	)