--SA SE ANALIZEZE PRETURILE LAPTOPURILOR SI IN FUNCTIE DE VALOAREA SA FIE GRUPATE IN 3 CATEGORII
--1. DACA PRETUL ESTE MAI IEFTIN DE 5000 DE LEI SE NUMESTE ECONOM
--2. DACA PRETUL VA FI CUPRINS INTRE 5000-8000 DE LEI SE NUMESTE BUSSINESS
--3. MAI MARE DE 8000 CLASA PREMIUM
USE DEPO

SELECT PRET,
	(
		CASE
		WHEN PRET<5000 THEN 'ECONOM'
		WHEN PRET BETWEEN 5000 AND 8000 THEN 'BUSINESS'
		ELSE 'PREMIUM'
		END
	) AS PRICE
	FROM LAPTOPURI

SELECT PRET,
	IIF(PRET<5000,'ECONOM',IIF(PRET BETWEEN 5000 AND 8000, 'BUSSINES','PREMIUM'))
	FROM LAPTOPURI

--DIN TABELUL PRODUSE SA SE OBTINA UN TABEL CU URM. COLOANE:
--1. PRODUCATOR, PC, IMRPIMANTE, LAPTOPURI.
--PENTRU FIECARE PRODUCATOR IN ACEST TABEL SA SE INDICE DACA PRODUCE SAU NU UN ANUMIT TIP DE PRODUSE
SELECT PRODUCATOR,
	(
		SELECT IIF(COUNT(*)>0,'DA','NU') FROM LAPTOPURI L INNER JOIN PRODUSE P ON L.MODEL_ID=P.MODEL_ID
		WHERE PP.PRODUCATOR=P.PRODUCATOR
	) AS TYPE_LAPTOPURI,
	(
		SELECT IIF(COUNT(*)>0,'DA','NU') FROM PC INNER JOIN PRODUSE P ON PC.MODEL_ID=P.MODEL_ID
		WHERE PP.PRODUCATOR=P.PRODUCATOR
	) AS TYPE_PC,
	(
		SELECT IIF(COUNT(*)>0,'DA','NU') FROM IMPRIMANTE I INNER JOIN PRODUSE P ON I.MODEL_ID=P.MODEL_ID
		WHERE PP.PRODUCATOR=P.PRODUCATOR
	) AS TYPE_IMPRIMANTA
	FROM PRODUSE PP
	GROUP BY PRODUCATOR

--SA SE GASEASCA TOTI ANGAJATII CE LOCUIESC IN CHISINAU SI PRIMESC UN SALARIU MAI MARE DECAT SALARIU MEDIU
USE ANGAJAT
SELECT NUME+' '+PRENUME as NUME,SALARIU
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
				   INNER JOIN LOC_STR LS ON LS.LOC_STR_ID=A.LOC_STR_ID
				   INNER JOIN LOCALITATE L ON L.LOCALITATE_ID=LS.LOCALITATE_ID
				   WHERE DATA_ELIBARARII IS NULL AND LOCALITATE LIKE '%CHI%'
				   AND SALARIU>(SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL)

--SA SE SCRIE O INTEROGARE PENTRU A OBTINE TOTI ANGAJATII CU VENITUL MAI MARE DECAT MEDIA ARITMETICA A 
--SALARIATILOR DIN DEPARTAMENTUL IT
SELECT NUME+' '+PRENUME AS ANGAJAT,SUM(SALARIU) AS SALARIU
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	WHERE DATA_ELIBARARII IS NULL
	AND SALARIU>(SELECT AVG(SALARIU) FROM ANGAJARE AA INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=AA.DEPARTAMENT_ID
	WHERE DENUMIRE='IT')
	GROUP BY NUME+' '+PRENUME

--SA SE GASEASCA CEA MAI SOLICITATA FUNCTIE
SELECT *
	FROM
(
	SELECT DENUMIRE_FUNCTIE,COUNT(*) AS NR
	FROM FUNCTIE F INNER JOIN ANGAJARE AA ON AA.FUNCTIE_ID=F.FUNCTIE_ID
	GROUP BY DENUMIRE_FUNCTIE
) AS X
	WHERE NR=
	(
		SELECT MAX(NR) FROM
		(
			SELECT DENUMIRE_FUNCTIE,COUNT(*) AS NR
			FROM FUNCTIE F INNER JOIN ANGAJARE AA ON AA.FUNCTIE_ID=F.FUNCTIE_ID
			GROUP BY DENUMIRE_FUNCTIE
		) AS Y
	)
--P/U
--SA SE SCRIE O INTEROGARE PENTRU A OBTINE DATELE STATISTICE:
--DEPARTAMENT:
--	1. NUMARUL DE PERSOANE CU SALARIUL PANA LA 5000 DE LEI
--	2. NUMARUL DE PERSOANE CU SALARIUL DE LA 5000 - 10000 LEI
--	3. NUMARUL DE PERSOANE CU SALARIUL MAI MARE 10000 LEI
--	4. SA SE CATEGORIZEZE (II BINE PLATITA),(BINE PLATITA),(FOARTE BINE PLATITA)
--SLAB SLAB PLATITA - MAI PUTIN DE 25000 DE MII
--BINE PLATITA - 25000-50000 LEI
--FOARTE BINE PLATITA - MAI MARE 50000 LEI