--STRUCTURA INTEROGARII--
SELECT CAMPURI
FROM TABELE
WHERE CONDITII
HAVING CONDITII DE GRUPARE
GROUP BY CAMPURI
ORDER BY CAMPURI [ASC/DESC]

--FUNCTII PREDEFINITE--
--1. FUNCTII DE RAND - CARE SE EXECUTA PENTRU FIECARE RAND IN PARTE
--2. FUNCTII DE GRUP - CARE SE EXECUTA PENTRU UN GRUP DE DATE

--	1	--
--FUNCTII DE PRELUCRARE A SIRURILOR DE CARACTERE--
	--1. FUNCTII CONCATENARE:
	--		CONCAT(CAMP1,CAMP2,...CAMPN)
USE DEPO
SELECT *,CONCAT(TIP,5,TIP) AS CONCATINARE,
	'5'+TIP AS CONCATE,
	5+5 AS SUMA,
	'5'+'5' AS SUMA2
	FROM PRODUSE 
--	2	--
--SUBSIR - SUBSTRING(CAMP,NR_SIMBOL_START,LUNGIMEA)
SELECT *,SUBSTRING(TIP,1,1) AS SUBSIR
	FROM PRODUSE

SELECT *,SUBSTRING(TIP,3,3) AS SUBSIR
	FROM PRODUSE
--	3	--
--LUNGIMEA - LEN(NUME_CAMP)
SELECT *,LEN(TIP) FROM PRODUSE

SELECT *,SUBSTRING(TIP,LEN(TIP),1) FROM PRODUSE

--FUNCTIA DE TRANSFORMARE IN SIMBOLURI MAJUSCULE - UPPER(NUME_CAMP)
--FUNCTIA DE TRANSFORMARE IN SIMBOLURI MINUSCULE - LOWER(NUME_CAMP)
SELECT *,LOWER(TIP),
	UPPER(LOWER(TIP))
	FROM PRODUSE

SELECT *, CONCAT(UPPER(SUBSTRING(TIP,1,1)),
	SUBSTRING(LOWER(TIP),2,LEN(TIP)-2),
	UPPER(SUBSTRING(TIP,LEN(TIP),1)))
	FROM IMPRIMANTE

--	4	--
--CONVERTIREA DATELOR - CAST(NUME_CAMP AS TIP_NOU_DE_DATE)
--CONVERT(TIP_NOU_DE_DATE,NUME_CAMP)
SELECT *,CAST(MODEL_ID AS VARCHAR(5))+TIP,
	ROUND(CONVERT(FLOAT,MODEL_ID)/3,2),
	CAST(MODEL_ID AS VARCHAR(5))+CAST(MODEL_ID AS VARCHAR(5))
	FROM PRODUSE

SELECT MODEL_ID,CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(4)),1,1) AS INT)+
	CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(4)),2,1)AS INT)+
	CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(4)),3,1)AS INT)+
	CAST(SUBSTRING(CAST(MODEL_ID AS VARCHAR(4)),4,1)AS INT) AS SUMA
	FROM PRODUSE

--FUNCTIILE DE GRUP--
--SUMA - SUM(CAMP)
--AVERAGE - AVG(CAMP)
--COUNT(*)
--MINIM - MIN(CAMP)
--MAXIM - MAX(CAMP)

SELECT SUM(MODEL_ID),
	AVG(MODEL_ID),
	MIN(MODEL_ID),
	MAX(MODEL_ID),
	COUNT(*)
	FROM PRODUSE