--TEMA: STUDIUL SELECTARII INFORMATII DIN BD
--PENTRU A SELECTA INFO DIN BD VOM FOLOSI
--URMATOAREA SINTAXA GENERALA:
--	SELECT NUME_TABELA.NUME_CAMP,...,NUME_TABELA_N.NUME_CAMP_N
--		FROM NUME_TABELA,...,NUME_TABELA_N
--				conditii obligatorii
--
--				conditii neobligatorii
--[WHERE CONDITII_DE_FILTRARE]
--[HAVING CONDITII_DE_FILTRARE GRUP]
--[GROUP BY GRUPARE_DATE]
--[ORDER BY NUME_TABELA.NUME_CAMP[ASC/DESC]] - cu el se incheie
--ASC - ASCENDENT, DESC - DESCENDENT
--				EXEMPLU:
/*
SELECT PRODUSE.MODEL_ID,PRODUSE.PRODUCATOR,PRODUSE.TIP
	FROM PRODUSE
*/
SELECT MODEL_ID,PRODUCATOR,TIP
	FROM PRODUSE
SELECT *,RAM+RAM,RAM,HDD FROM PC

--PRELUCRAREA CAMPURILOR SELECTULUI
--1. REDENUMIREA CAMPULUI
SELECT *,RAM+RAM AS SUMA_RAM,RAM,HDD FROM PC
SELECT *,RAM+RAM AS 'SUMA RAM',RAM,HDD FROM PC
SELECT *,RAM+RAM SUMA_RAM,RAM,HDD FROM PC

--SA SE SCRIE O INTEROGARE CE VA CALCULA -20% DIN PRETUL PC-URILOR

SELECT *,PRET*0.2 AS REDUCERE,PRET-(PRET*0.2) AS PRETFIN
	FROM PC


