USE ANGAJAT
SELECT NUME+' '+PRENUME AS NPP,SUM(SALARIU) AS SALARIUL
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	GROUP BY NUME+' '+PRENUME
	ORDER BY NPP

SELECT NUME,PRENUME,RAION
	FROM ANGAJAT A INNER JOIN LOC_STR LS ON A.LOC_STR_ID=LS.LOC_STR_ID
				   INNER JOIN LOCALITATE L ON L.LOCALITATE_ID=LS.LOCALITATE_ID
				   INNER JOIN RAION R ON R.RAION_ID=L.RAION_ID
				   ORDER BY RAION,NUME

SELECT RAION,COUNT(*)
	FROM ANGAJAT A INNER JOIN LOC_STR LS ON LS.LOC_STR_ID=A.LOC_STR_ID
				   INNER JOIN LOCALITATE L ON L.LOCALITATE_ID=LS.LOCALITATE_ID
				   INNER JOIN RAION R ON R.RAION=L.RAION_ID
				   GROUP BY RAION

SELECT DENUMIRE,SUM(SALARIU+BONUS_SALARIU-PENALITATI_SALARIU) AS SAL
	FROM DEPARTAMENT D INNER JOIN ANGAJARE A ON A.DEPARTAMENT_ID=D.DEPARTAMENT_ID
	WHERE DATA_ELIBARARII IS NULL
	GROUP BY DENUMIRE

SELECT RAION,SUM(SALARIU) AS SALARIU_BRUT,SUM(SALARIU-SALARIU*0.2) AS SALARIU_NETE
	FROM ANGAJARE A INNER JOIN ANGAJAT AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
				    INNER JOIN LOC_STR LS ON LS.LOC_STR_ID=AA.LOC_STR_ID
					INNER JOIN LOCALITATE L ON L.LOCALITATE_ID=LS.LOCALITATE_ID
					INNER JOIN RAION R ON R.RAION_ID=L.RAION_ID
					GROUP BY RAION

SELECT NUME+' '+PRENUME,SUM(SALARIU)
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	WHERE SUBSTRING(NUME,LEN(NUME),1) IN ('A','E')
	GROUP BY NUME+' '+PRENUME

SELECT NUME,SALARIU
	FROM ANGAJARE AA INNER JOIN ANGAJAT A ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	WHERE SALARIU>(BONUS_SALARIU-PENALITATI_SALARIU)

SELECT DENUMIRE_FUNCTIE,SALARIU
	FROM FUNCTIE F INNER JOIN ANGAJARE AA ON F.FUNCTIE_ID=AA.FUNCTIE_ID
	WHERE SALARIU%2=0 AND CAST(SUBSTRING(CAST(SALARIU AS VARCHAR(10)),1,1) AS INT)%2=0 AND
	CAST(SUBSTRING(CAST(SALARIU AS VARCHAR(10)),1,1) AS INT)%2!=0

SELECT RAION,LOCALITATE,NUME+' '+PRENUME AS NUME,NUME_STRADA,DENUMIRE_FUNCTIE,DENUMIRE
	FROM RAION R INNER JOIN LOCALITATE L ON R.RAION_ID=L.RAION_ID
				 INNER JOIN LOC_STR LS ON LS.LOCALITATE_ID=L.LOCALITATE_ID
				 INNER JOIN STRADA S ON S.STRADA_ID=LS.STRADA_ID
				 INNER JOIN ANGAJAT A ON A.LOC_STR_ID=LS.LOC_STR_ID
				 INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
				 INNER JOIN FUNCTIE F ON F.FUNCTIE_ID=AA.FUNCTIE_ID
				 INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=AA.DEPARTAMENT_ID