USE ANGAJAT
UPDATE ANGAJARE
	SET DATA_ANGAJARII=GETDATE()-ANGAJARE_ID
UPDATE ANGAJARE
	SET DATA_ELIBARARII=GETDATE()+ANGAJARE_ID
	WHERE ANGAJARE_ID IN(24,30,13,43)

--PENTRU FIECARE ANGAJAT SA SE INDICE SALARIUL TOTAL
SELECT NUME+' '+PRENUME AS NPP,SUM(SALARIU) AS SALARIUL
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON
	A.ANGAJAT_ID=AA.ANGAJAT_ID
	GROUP BY NUME+' '+PRENUME
	ORDER BY NPP

--SA SE ARATE PENTRU FIECARE ANGAJAT DIN CE RAION FACE PARTE
SELECT NUME,PRENUME,RAION
	FROM ANGAJAT A INNER JOIN LOC_STR L ON A.LOC_STR_ID=L.LOC_STR_ID
	INNER JOIN LOCALITATE LL ON LL.LOCALITATE_ID=L.LOCALITATE_ID
	INNER JOIN RAION R ON R.RAION_ID=LL.RAION_ID
	ORDER BY RAION,NUME

--PENTRU FIECARE RAION SA SE INDICE NUMARUL DE PERSOANE
SELECT RAION,COUNT(*) 
	FROM ANGAJAT A INNER JOIN LOC_STR S ON A.LOC_STR_ID=S.LOC_STR_ID 
	INNER JOIN LOCALITATE L ON L.LOCALITATE_ID=S.LOCALITATE_ID
	INNER JOIN RAION R ON R.RAION_ID=L.RAION_ID
	GROUP BY RAION

--PENTRU FIECARE DEPARTAMENT SA SE INDICE NUMARUL DE PERSOANE
SELECT DENUMIRE,COUNT(*) AS PERSONE
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	INNER JOIN DEPARTAMENT D ON AA.DEPARTAMENT_ID=D.DEPARTAMENT_ID
	GROUP BY DENUMIRE

--PENTRU FIECARE DEPARTAMENT SA SE INDICE SUMA CHELTUIELILOR SALARIALE
SELECT DENUMIRE,SUM(SALARIU+BONUS_SALARIU-PENALITATI_SALARIU) AS SALARIU
	FROM DEPARTAMENT D INNER JOIN ANGAJARE A ON D.DEPARTAMENT_ID=A.DEPARTAMENT_ID
	WHERE DATA_ELIBARARII IS NULL
	GROUP BY DENUMIRE

--PENTRU FIECARE RAION SA SE INDICE CHELTUIELILE SALARIALE BRUTE SI NETE
SELECT RAION,SUM(SALARIU) AS SALARIU_BRUT, SUM(SALARIU-SALARIU*0.2) AS SALARIU_NETE
	FROM ANGAJARE A INNER JOIN ANGAJAT AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
	INNER JOIN LOC_STR L ON L.LOC_STR_ID=AA.LOC_STR_ID
	INNER JOIN LOCALITATE LI ON L.LOCALITATE_ID=LI.LOCALITATE_ID
	INNER JOIN RAION R ON R.RAION_ID=LI.RAION_ID
	GROUP BY RAION

--SA SE GASEASCA NUMELE SI SALARIUL TOTAL A PERSOANELOR A CAROR NUME SE
-- TERMINA IN A SI E
SELECT NUME+' '+PRENUME,SUM(SALARIUL)
	FROM ANGAJARE A INNER JOIN ANGAJAT AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
--	WHERE NUME LIKE '%A' OR NUME LIKE '%E'
	WHERE SUBSTRING(NUME,LEN(NUME),1) IN ('A','E')
	GROUP BY NUME+' '+PRENUME

--SA SE AFISEZE TOTI ANGAJATII CE PRIMESC UN SALARIU MAI MIC 
--DE DEIFERENTA DINTRE BONUS SI PENALITATI
SELECT NUME,SALARIU
	FROM ANGAJARE AA INNER JOIN ANGAJAT A ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	WHERE SALARIU>(BONUS_SALARIU-PENALITATI_SALARIU)

--SA NE AFISEZE ACELE FUNCTII LA CARE SALARIUL ESTE O CIFRA PARA SI LA CARE PRIMA SI 
--ULTIMA CIFRA DIN COMPONENTA SALARIULUI ESTE MAI MARE
SELECT DENUMIRE_FUNCTIE,SALARIU
	FROM FUNCTIE F INNER JOIN ANGAJARE A ON F.FUNCTIE_ID=A.FUNCTIE_ID
	WHERE SALARIU%2=0 AND CAST(SUBSTRING(CAST(SALARIU AS VARCHAR(10)),1,1)AS INT)%2=0 AND
	CAST(SUBSTRING(CAST(SALARIU AS VARCHAR(10)),LEN(CAST(SALARIU AS VARCHAR(10))),1)AS INT)%2!=0

--YEAR,DAY AND MONTH
SELECT DATA_ANGAJARII,YEAR(DATA_ANGAJARII) AS AN,MONTH(DATA_ANGAJARII) AS LUNA, DAY(DATA_ANGAJARII) AS ZI
	FROM ANGAJARE

--SA FACEM INNER JOIN INTRE TOATE TABELE BD
--PENTRU FIECARE ANGAJAT SA SE CALCULEZE VIRSTA IN ANI,LUNI,ZILE
SELECT RAION,LOCALITATE,NUME+' '+PRENUME AS NUME,NUME_STRADA,DENUMIRE_FUNCTIE,DENUMIRE
	FROM RAION R INNER JOIN LOCALITATE L ON R.RAION_ID=L.RAION_ID
	INNER JOIN LOC_STR LL ON LL.LOCALITATE_ID=L.LOCALITATE_ID
	INNER JOIN STRADA S ON S.STRADA_ID=LL.STRADA_ID
	INNER JOIN ANGAJAT A ON LL.LOC_STR_ID=A.LOC_STR_ID
	INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	INNER JOIN FUNCTIE F ON F.FUNCTIE_ID=AA.FUNCTIE_ID
	INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=AA.DEPARTAMENT_ID
	