--SA SE GASEASCA PC-UL CU PRET MAXIM
SELECT MAX(PRET) FROM PC
SELECT * FROM PC 
WHERE PRET=(SELECT MAX(PRET) FROM PC)

--PENTRU FIECARE PRODUCATOR DE PC SA SE INDICE NUMARUL DE MODELE
SELECT PRODUCATOR, COUNT(DISTINCT(P.MODEL_ID)) AS NR FROM PRODUSE P
INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
GROUP BY PRODUCATOR

SELECT PRODUCATOR,
	(SELECT COUNT(DISTINCT(PP.MODEL_ID))FROM PC
	INNER JOIN PRODUSE PP ON PP.MODEL_ID=PC.MODEL_ID
	WHERE PP.PRODUCATOR=P.PRODUCATOR) AS NR FROM PRODUSE P
	WHERE TIP='PC'
	GROUP BY PRODUCATOR

--PENTRU FIECARE VITEZA DE LAPTOP SA SE CALCULEZE SUMA SI CANTITATEA
SELECT L.VITEZA,
	(SELECT SUM(PRET) FROM LAPTOPURI LL WHERE LL.VITEZA=L.VITEZA) AS SUMA,
	(SELECT COUNT(*) FROM LAPTOPURI LT WHERE LT.VITEZA=L.VITEZA) AS CANT
	FROM LAPTOPURI L
	GROUP BY L.VITEZA

--PENTRU FIECARE ANGAJAT SA SE CALZULEZE SUMA TOTALA A SALARIULUI
SELECT ANGAJAT_ID,NUME+' '+PRENUME AS NUME,
	(SELECT SUM(SALARIU) FROM ANGAJARE A WHERE AA.ANGAJAT_ID=A.ANGAJAT_ID AND DATA_ELIBARARII IS NULL) AS SALARIUL
	FROM ANGAJAT AA

--PENTRU FIECARE RAION SA SE CALCULEZE NUMARUL DE ANGAJATI

USE ANGAJAT
SELECT RAION_ID,RAION,
(SELECT COUNT(DISTINCT(A.ANGAJAT_ID)) FROM RAION RR INNER JOIN LOCALITATE L ON RR.RAION_ID=L.RAION_ID
												    INNER JOIN LOC_STR LS ON L.LOCALITATE_ID=LS.LOCALITATE_ID
												    INNER JOIN ANGAJAT A ON A.LOC_STR_ID=LS.LOC_STR_ID
												    INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
												    WHERE RR.RAION_ID=R.RAION_ID) AS NR
FROM RAION R
ORDER BY NR DESC




SELECT A.ANGAJAT_ID FROM RAION RR INNER JOIN LOCALITATE L ON RR.RAION_ID=L.RAION_ID
												    INNER JOIN LOC_STR LS ON L.LOCALITATE_ID=LS.LOCALITATE_ID
												    INNER JOIN ANGAJAT A ON A.LOC_STR_ID=LS.LOC_STR_ID
												    INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
													ORDER BY A.ANGAJAT_ID
												    
	USE DEPO												
--SA SE GASEASCA PRODUSUL CEL MAI SCUMP
SELECT VIRT.*
FROM
(
	SELECT 'PC' AS TIP,MODEL_ID,PRET,VITEZA,HDD FROM PC
	UNION
	SELECT 'LAPTOP' AS TIP,MODEL_ID,PRET,VITEZA,HDD FROM LAPTOPURI
	UNION
	SELECT 'IMPRIMANTE' AS TIP,MODEL_ID,PRET,0,0 FROM IMPRIMANTE
) VIRT
WHERE PRET=(
	SELECT MAX(V.PRET)
	FROM
	(
		SELECT 'PC' AS TIP,MODEL_ID,PRET,VITEZA,HDD FROM PC
		UNION
		SELECT 'LAPTOP' AS TIP,MODEL_ID,PRET,VITEZA,HDD FROM LAPTOPURI
		UNION
		SELECT 'IMPRIMANTE' AS TIP,MODEL_ID,PRET,0,0 FROM IMPRIMANTE
	) V
	)

--SA SE GASEASCA LAPTOPURILE A CAROR VITEZA ESTE MAI MICA DECAT LA ORICE PC
--SA SE AFISEZE TIPUL,MODELUL SI VITEZA
SELECT MODEL_ID,VITEZA FROM LAPTOPURI
WHERE VITEZA<(SELECT MAX(VITEZA) FROM PC)

P/U
--SA SE GASEASCA PRODUCATORII CELOR MAI SCUMPE LAPTOPURI SAU PC-URI, AFISATI PRODUCATOR, MODEL SI PRET
--SA SE GASEASCA HDD CARE COINCID CU 2 SAU MAI MULTE PC-URI
--PENTRU FIECARE DEPARTAMENT SA SE AFLE:
--1. NUMARUL DE PERSOANE ANGAJATE
--2. NUMARUL DE PERSOANE ELIBERATE
--3. SUMA SALARIILOR PERSOANELOR ANGAJATE
--4. SA SE GASEASCA CEL MAI BINE PLATIT SI CEL MAI PROST PLATIT ANGAJAT
USE ANGAJAT
SELECT * FROM ANGAJARE