USE ANGAJAT

SELECT SALARIU,
(
	CASE 
	WHEN SALARIU<5000 THEN 'SLAB PLATIT'
	WHEN SALARIU BETWEEN 5000 AND 10000 THEN 'BINE PLATIT'
	WHEN SALARIU>10000 THEN 'FOARTE BINE PLATIT'
	END
) AS STATISTIC
FROM ANGAJARE
