USE DEPO

SELECT * 
	FROM PRODUSE P LEFT JOIN PC ON P.MODEL_ID=PC.MODEL_ID

SELECT *
	FROM PRODUSE P RIGHT JOIN PC ON P.MODEL_ID=PC.MODEL_ID

SELECT *
	FROM PRODUSE P FULL JOIN PC ON P.MODEL_ID=PC.MODEL_ID

SELECT *
	FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
				   INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID

SELECT TIP,PRET
	FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
UNION
SELECT TIP,PRET 
	FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID

SELECT TIP,PRET
	FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
UNION ALL
SELECT TIP,PRET
	FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID

SELECT VITEZA AS V,PRET
	FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
UNION
SELECT VITEZA,PRET
	FROM PRODUSE P INNER JOIN LAPTOPURI L ON P.MODEL_ID=L.MODEL_ID
UNION 
SELECT 0,PRET
	FROM PRODUSE P INNER JOIN IMPRIMANTE I ON I.MODEL_ID=P.MODEL_ID

SELECT TIP,PRET,CD
	FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
UNION
SELECT TIP,PRET,'-'
	FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID
UNION
SELECT P.TIP,PRET,'-'
	FROM PRODUSE P INNER JOIN IMPRIMANTE I ON P.MODEL_ID=I.MODEL_ID

SELECT VITEZA
	FROM PC
EXCEPT
SELECT VITEZA
	FROM LAPTOPURI

SELECT VITEZA
	FROM PC
INTERSECT
SELECT VITEZA
	FROM LAPTOPURI

SELECT PRODUCATOR
	FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
INTERSECT
SELECT PRODUCATOR
	FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID
EXCEPT
SELECT PRODUCATOR
	FROM PRODUSE P INNER JOIN IMPRIMANTE I ON I.MODEL_ID=P.MODEL_ID