USE DEPO

SELECT * FROM PRODUSE P LEFT JOIN PC ON P.MODEL_ID=PC.MODEL_ID --WHERE PC.MODEL_ID IS NULL

SELECT * FROM PRODUSE P RIGHT JOIN PC ON P.MODEL_ID=PC.MODEL_ID --WHERE PC.MODEL_ID IS NULL

SELECT * FROM PRODUSE P FULL JOIN PC ON P.MODEL_ID=PC.MODEL_ID --WHERE PC.MODEL_ID IS NULL

--SA SE AFISEZE LISTA TUTUROR PRODUSELOR
SELECT * FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
						INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID

SELECT * FROM LAPTOPURI

--STUDIUL UNION - UNIFICA REZULTATUL A DOUA SI MAI MULTE INTEROGARI DACA SE RESPECTA URMATOARELE 2 CONDITII:
--1. NUMARUL DE CAMPURI SA FIE EGAL PENTRU TOATE SELECTURILE
--2. TIPUL DE DATE SA CONINCIDA
SELECT TIP,PRET FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
UNION
SELECT TIP,PRET FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID

--UNION ESTE DE 2 TIPURI:
--1. UNION - NE DA RASPUNSUL FARA REPETARI DIN REZULTATUL OBTINUT
--2. UNION ALL - NE DA TOATE INREGISTRARILE

SELECT TIP,PRET FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
UNION ALL
SELECT TIP,PRET FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID

--SA SE AFISEZE PRETUL SI VITEZA PRODUSELOR
SELECT VITEZA AS V,PRET FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
UNION
SELECT VITEZA,PRET FROM PRODUSE P INNER JOIN LAPTOPURI L ON P.MODEL_ID=L.MODEL_ID
UNION
SELECT 0,PRET FROM PRODUSE P INNER JOIN IMPRIMANTE I ON I.MODEL_ID=P.MODEL_ID

--PENTRU TOATE PRODUSELE SA SE AFISEZE URMATOARELE INFORMATIE: TIP,PRETUL,CD
SELECT TIP,PRET,CD FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
UNION ALL
SELECT P.TIP,PRET,'-' FROM PRODUSE P INNER JOIN IMPRIMANTE I ON P.MODEL_ID=P.MODEL_ID
UNION ALL
SELECT TIP,PRET,'-' FROM PRODUSE P INNER JOIN LAPTOPURI ON P.MODEL_ID=P.MODEL_ID

--STUDIUL EXCEPT(MINUS/DIFERENCE) - FACE EXCEPTIE 
--1. NUMARUL DE CAMPURI SA FIE EGAL PENTRU TOATE SELECTURILE
--2. TIPUL DE DATE SA CONINCIDA

--SA SE AFISEZE VITEZELE DIN PC CARE NU SUNT IN LAPTOPURI
SELECT VITEZA FROM PC
EXCEPT 
SELECT VITEZA FROM LAPTOPURI

--STUDIUL INTERSECT - IA VALORILE COMUNE
--1. NUMARUL DE CAMPURI SA FIE EGAL PENTRU TOATE SELECTURILE
--2. TIPUL DE DATE SA CONINCIDA
SELECT VITEZA FROM PC
INTERSECT 
SELECT VITEZA FROM LAPTOPURI

--SA SE GASEASCA PRODUCATORII DE PC-URI SI LAPTOPURI CARE NU PRODUC IMRPIMANTE
SELECT PRODUCATOR FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
INTERSECT
SELECT PRODUCATOR FROM PRODUSE P INNER JOIN LAPTOPURI L ON P.MODEL_ID=L.MODEL_ID
EXCEPT
SELECT PRODUCATOR FROM PRODUSE P INNER JOIN IMPRIMANTE I ON P.MODEL_ID=I.MODEL_ID	