USE DEPO
SELECT SUM(PRET) AS SUMA_VIT,
	AVG(PRET),
	SUM(PRET)/COUNT(*),
	MIN(PRET),
	MAX(PRET)
	FROM LAPTOPURI

SELECT DISTINCT(PRODUCATOR),
	TIP
	FROM PRODUSE

SELECT PRODUCATOR,
	TIP
	FROM PRODUSE

SELECT PRODUCATOR,
	TIP
	FROM PRODUSE GROUP BY PRODUCATOR, TIP

--SA SE DETERMINE NUMARUL DE PRODUSE PENTRU FIECARE PRODUCATOR IN PARTE
SELECT PRODUCATOR,
	COUNT(*) AS NR 
	FROM PRODUSE 
	GROUP BY PRODUCATOR

SELECT PRODUCATOR,
	TIP,
	COUNT(*) AS NR
	FROM PRODUSE
	GROUP BY PRODUCATOR,TIP

SELECT COLOR,
	COUNT(*) AS NUMAR,
	SUM(PRET) AS SUMA_PRET
--	TIP,
--	COUNT(*) AS NUMAR1
--	PRET,
--	COUNT(PRET) AS NUMAR2
	FROM IMPRIMANTE
	GROUP BY COLOR--,TIP,PRET

SELECT TIP,
	COUNT(*) AS NUMAR1,
	SUM(PRET) AS SUMA1_PRET
	FROM IMPRIMANTE
	GROUP BY TIP

SELECT TIP,
	COLOR,
	COUNT(*) AS NR,
	SUM(PRET) AS NUMAR_PRET3
	FROM IMPRIMANTE
	GROUP BY TIP,COLOR


USE DEPO
SELECT * FROM PC
SELECT MODEL_ID,SUM(PRET) AS SUMA FROM PC GROUP BY MODEL_ID HAVING SUM(PRET)>=3000



-----	TEMA STUDIULUI CLAUZEI WHERE	-----
--	O INTEROGARE POATE FI ALCATUITA DIN UNA SAU MAI MULTE CONDITII
--	SI SE APLICA MULTITUDINEA DE OPERATORI:
--		1. OPERATORI DE COMPARARE =,<,>,<=,>=,<>,!=
--		2. OPERATORI LOGICI AND,OR,NOT
--		3. FUNCTII BETWEEN,IN,LIKE
SELECT * FROM PC WHERE PRET>4000

SELECT * FROM IMPRIMANTE WHERE COLOR='NU'

--SA SE GASEASCA UNDE VITEZA ESTE MAI MICA DE 3000 MHz
SELECT * FROM PC WHERE VITEZA<3000

SELECT * FROM PC WHERE HDD!=500
SELECT *
	FROM PC
	WHERE VITEZA>=2000 AND VITEZA<=3000

SELECT *
	FROM PC
	WHERE VITEZA BETWEEN 2000 AND 3000

SELECT *
	FROM PC
	WHERE CD='12X' OR CD='24X'

SELECT *
	FROM PC
	WHERE CD IN('12X','24X')

SELECT *
	FROM LAPTOPURI
	WHERE ECRAN>=13 AND HDD>=500

--SA SE GASEASCA PC-URILE A CAROR PRET NU DEPASESTE 8000 DE LEI SI CU HDD CUPRINS INTRE 500 SI 1000 DE MGB
SELECT * FROM PC WHERE PRET<=8000 AND HDD BETWEEN 500 AND 1000

SELECT *
	FROM PC
	WHERE VITEZA BETWEEN 2000 AND 4000 AND (CD='24X' OR CD='40X' OR CD='52X')



SELECT *
	FROM PC
	WHERE VITEZA BETWEEN 2000 AND 4000 AND CD NOT IN('24X','40X','52X')