USE DEPO
SELECT *
	FROM PC WHERE PRET < 5000

SELECT * 
	FROM IMPRIMANTE WHERE TIP = 'JET'

SELECT * FROM IMPRIMANTE
	WHERE PRET > 900

SELECT * FROM IMPRIMANTE
	WHERE PRET > 900 AND COLOR != 'DA'

SELECT * FROM LAPTOPURI
	WHERE VITEZA > 2200

SELECT * FROM LAPTOPURI
	WHERE HDD > 1000

SELECT * FROM LAPTOPURI
	WHERE ECRAN >= 14

SELECT VITEZA,
	COUNT(*) AS NUMAR1
	FROM LAPTOPURI
	GROUP BY VITEZA

SELECT PRET,
	COUNT(*) AS NUMAR1
	FROM LAPTOPURI
	GROUP BY PRET

SELECT VITEZA,
	ECRAN,
	COUNT(*) AS NR,
	SUM(PRET) AS NUMAR_PRET3
	FROM LAPTOPURI
	GROUP BY VITEZA, ECRAN

SELECT VITEZA,
	COUNT(*) AS NR_VITEZA,
	ECRAN,
	COUNT(*) AS NR_ECRAN
	FROM LAPTOPURI
	GROUP BY VITEZA, ECRAN

SELECT * FROM PC
	WHERE PRET BETWEEN 6000 AND 9000

SELECT * FROM PC
	WHERE CD IN('52X', '40X')

SELECT * FROM PC
	WHERE PRET <= 8000 AND RAM BETWEEN 2000 AND 4000

SELECT * FROM PC
	WHERE VITEZA = 3000 AND RAM >= 2000 AND HDD <=1000

SELECT CD,
	COUNT(*) AS NUMAR_CD
	FROM PC
	GROUP BY CD
