--SA SCRIE O INTEROGARE CE VA AFISA ANGAJATII IN MAJUSCULA CU MEDIILE SALARIILOR NEAFILIATE LA FUNCTIA CARE O DETINE LA MOMENT
SELECT NAME,CAST(SAL_FONCTION AS DECIMAL(8,2)) AS M FROM 
(
	SELECT NUME+' '+UPPER(SUBSTRING(PRENUME,1,1))+LOWER(SUBSTRING(PRENUME,2,LEN(PRENUME))) AS NAME,FUNCTIE_ID,
	(SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL AND FUNCTIE_ID!=AA.FUNCTIE_ID) AS SAL_FONCTION 
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
) X
--SA SE AFISEZE PERSOANA CU CEL MAI MARE SALARIU OBTINUT DIN PUNCTUL ANTERIOR


SELECT NAME,CAST(SAL_FONCTION AS DECIMAL(8,2)) AS SALARIU FROM 
(
	SELECT NUME+' '+UPPER(SUBSTRING(PRENUME,1,1))+LOWER(SUBSTRING(PRENUME,2,LEN(PRENUME))) AS NAME,FUNCTIE_ID,
	(SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL AND FUNCTIE_ID!=AA.FUNCTIE_ID) AS SAL_FONCTION 
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
) X
WHERE SAL_FONCTION=
(
	SELECT MAX(SAL_FONCTION) FROM
	(
		SELECT NUME+' '+UPPER(SUBSTRING(PRENUME,1,1))+LOWER(SUBSTRING(PRENUME,2,LEN(PRENUME))) AS NAME,FUNCTIE_ID,
		(SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL AND FUNCTIE_ID!=AA.FUNCTIE_ID) AS SAL_FONCTION 
		FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	) X
) 

SELECT * FROM ANGAJARE WHERE SALARIU=
(
	SELECT MAX(SALARIU) FROM ANGAJARE
)

--SA SE AFISEZE DEPARTAMENTUL CU MAXIM PERSOANE ANGAJATE
--DEPARTAMENT SI NR. PERSOANE ANGAJATE

SELECT * FROM
(
	SELECT DENUMIRE,
		(SELECT COUNT(*) FROM ANGAJARE A INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=A.DEPARTAMENT_ID
		WHERE D.DENUMIRE=DD.DENUMIRE) AS NR
		FROM DEPARTAMENT DD
) VIRTUAL

WHERE NR=
(
	SELECT MAX(NR) FROM
	(
		SELECT DENUMIRE,
			(SELECT COUNT(*) FROM ANGAJARE A INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=A.DEPARTAMENT_ID
			WHERE D.DENUMIRE=DD.DENUMIRE) AS NR
			FROM DEPARTAMENT DD
	) VIRTUAL
)

--SA SE GASEASCA LISTA PERSOANELOR DIN CADRUL DEPARTAMENTULUI IT
SELECT *
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
				   INNER JOIN DEPARTAMENT D ON AA.DEPARTAMENT_ID=D.DEPARTAMENT_ID
				   WHERE D.DENUMIRE='IT'
				   ORDER BY NUME
SELECT * 
	FROM ANGAJAT
	WHERE ANGAJAT_ID IN
	(
		SELECT ANGAJAT_ID 
			FROM ANGAJARE AA INNER JOIN DEPARTAMENT D ON AA.DEPARTAMENT_ID=D.DEPARTAMENT_ID
			WHERE D.DENUMIRE='IT'
	)

SELECT *
	FROM ANGAJAT
	WHERE ANGAJAT_ID IN
	(
		SELECT ANGAJAT_ID
			FROM ANGAJAT AA INNER JOIN LOC_STR LS ON AA.LOC_STR_ID=LS.LOC_STR_ID
							INNER JOIN LOCALITATE L ON LS.LOCALITATE_ID=L.LOCALITATE_ID
							WHERE LOCALITATE LIKE '%CHI%'
	)