USE ANGAJAT

SELECT NAME,CAST(SAL_FONCTION AS DECIMAL(8,2)) AS M
	FROM
	(
		SELECT NUME+' '+UPPER(SUBSTRING(PRENUME,1,1))+LOWER(SUBSTRING(PRENUME,2,LEN(PRENUME))) AS NAME,FUNCTIE_ID,
		(
			SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL
			AND FUNCTIE_ID!=AA.FUNCTIE_ID
		) AS SAL_FONCTION
		FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	) X

SELECT NAME,CAST(SAL_FONCTION AS DECIMAL(8,2)) AS M
	FROM
	(
		SELECT NUME+' '+UPPER(SUBSTRING(PRENUME,1,1))+LOWER(SUBSTRING(PRENUME,2,LEN(PRENUME))) AS NAME,FUNCTIE_ID,
		(
			SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL
			AND FUNCTIE_ID!=AA.FUNCTIE_ID
		) AS SAL_FONCTION
		FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	) X
WHERE SAL_FONCTION=
(
	SELECT MAX(SAL_FONCTION)
		FROM
		(
			SELECT NUME+' '+UPPER(SUBSTRING(PRENUME,1,1))+LOWER(SUBSTRING(PRENUME,2,LEN(PRENUME))) AS NAME,FUNCTIE_ID,
			(
				SELECT AVG(SALARIU) FROM ANGAJARE WHERE DATA_ELIBARARII IS NULL
				AND FUNCTIE_ID!=AA.FUNCTIE_ID
			) AS SAL_FONCTION
			FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
		) X
)


SELECT *
	FROM
	(
		SELECT DENUMIRE,
		(
			SELECT COUNT(*)
				FROM ANGAJARE A INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=A.DEPARTAMENT_ID
				WHERE D.DENUMIRE=DD.DENUMIRE
		) AS NR
		FROM DEPARTAMENT DD
	) VIRTUAL
WHERE NR=
(
	SELECT MAX(NR)
		FROM
		(
			SELECT DENUMIRE,
			(
				SELECT COUNT(*)
					FROM ANGAJARE A INNER JOIN DEPARTAMENT D ON D.DEPARTAMENT_ID=A.DEPARTAMENT_ID
					WHERE D.DENUMIRE=DD.DENUMIRE
			) AS NR
			FROM DEPARTAMENT DD
		) VIRTUAL
)

SELECT *
	FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	INNER JOIN DEPARTAMENT D ON AA.DEPARTAMENT_ID=D.DEPARTAMENT_ID
	WHERE D.DENUMIRE='IT'
	ORDER BY NUME