--SA SE GASEASCA DIMENSIUNEA MEDIE A ECRANILOR
--LAPTOPURILOR PRODUSE DE FIECARE PRODUCATOR IN PARTE
--SA SE AFISEZE 

SELECT PRODUCATOR,
(
	SELECT AVG(ECRAN) FROM LAPTOPURI L INNER JOIN PRODUSE P ON P.MODEL_ID=L.MODEL_ID
	WHERE P.PRODUCATOR=PP.PRODUCATOR
) DIMENSIUNE
FROM PRODUSE PP
GROUP BY PRODUCATOR

--SA SE GASEASCA PRODUCATORII CARE PRODUC CEL PUTIN 3 PC-URI
--AFLATI PRODUCATOR SI NUMAR DE MODELE

SELECT PRODUCATOR,
(
	SELECT COUNT(DISTINCT(PC.MODEL_ID)) FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
	WHERE PP.PRODUCATOR=P.PRODUCATOR
) NUMERE
FROM PRODUSE PP
GROUP BY PRODUCATOR
HAVING 
(
	SELECT COUNT(DISTINCT(PC.MODEL_ID)) FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
	WHERE PP.PRODUCATOR=P.PRODUCATOR
)>1

--SA SE GASEASCA PRETUL MAXIMAL AL PC-URILOR PRODUSE DE FIECARE PRODUCATOR IN PARTE
SELECT PRODUCATOR,
(
	SELECT MAX(PRET) FROM PC INNER JOIN PRODUSE P ON P.MODEL_ID=PC.MODEL_ID
	WHERE P.PRODUCATOR=PP.PRODUCATOR
) PRET_MAX
FROM PRODUSE PP
GROUP BY PRODUCATOR
HAVING
(
	SELECT MAX(PRET) FROM PC INNER JOIN PRODUSE P ON P.MODEL_ID=PC.MODEL_ID
	WHERE P.PRODUCATOR=PP.PRODUCATOR
) IS NOT NULL

--PENTRU FIECARE VALOARE A VITEZEI PC-ULUI CE DEPASESTE DE 2000 Mhz	SA SE 
--DETERMINE PRETUL MEDIU AL LAPTOPULUI CU ACEEASI VITEZA
USE DEPO
SELECT VITEZA,
(
	SELECT AVG(PRET) FROM LAPTOPURI L WHERE L.VITEZA=PC.VITEZA
) SUMA
FROM PC WHERE VITEZA>2000
GROUP BY VITEZA
HAVING
(
	SELECT AVG(PRET) FROM LAPTOPURI L WHERE L.VITEZA=PC.VITEZA
) IS NOT NULL

--AFISAREA TUTUROR PRODUCATORILOR CE PRODUC PC-URI SI LAPTOPURI CARE DESPUN DE VITEZA
--NU MAI MICA DE 2000Mhz

SELECT PRODUCATOR
	FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID
	WHERE VITEZA>=2000
INTERSECT
SELECT PRODUCATOR
	FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
	WHERE VITEZA>=2000

--SA SE GASEASCA PRODUCATORII DE IMPRIMANTE CARE PRODUC SI PC-URI CU CEL MAI MIC
--VOLUM RAM

SELECT PRODUCATOR
	FROM PRODUSE P INNER JOIN IMPRIMANTE I ON P.MODEL_ID=I.MODEL_ID
INTERSECT
SELECT PRODUCATOR
	FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
	WHERE RAM=
	(
		SELECT MIN(RAM) FROM PC
	)

SELECT PRODUCATOR
	FROM IMPRIMANTE I INNER JOIN PRODUSE P ON P.MODEL_ID=I.MODEL_ID
	WHERE PRODUCATOR IN
	(
		SELECT PRODUCATOR FROM PC INNER JOIN PRODUSE P ON P.MODEL_ID=PC.MODEL_ID
		WHERE RAM=
		(
			SELECT MIN(RAM) FROM PC
		)
	)
	GROUP BY PRODUCATOR

--STUDIUL LIMBAJULUI T-SQL
--SQL+IF+CASE+FOR+WHILE+...+=T-SQL

--IIF - IF PRESCURTAT
SELECT NUME,PRENUME,DATA_NASTERII,
	IIF(GEN=1,'M','F') AS GEN,
	(
		CASE
		WHEN GEN=1 THEN 'M'
		ELSE 'F'
		END
	) AS GEN2,
	(
		CASE
		WHEN GEN=1 THEN 'M'
		WHEN GEN=0 THEN 'F'
		END
	) AS GEN3
	FROM ANGAJAT

--CASE - SWITCH
(CASENUME_CAMP WHEN VALOARE THEN 'REZULTAT' WHEN VALOAREA2 THEN 'REZULTAT2' [ELSE]...END)

SELECT NUME,PRENUME,DATA_NASTERII,DAY(DATA_NASTERII) AS ZI,
(
	CASE
	MONTH(DATA_NASTERII)
	WHEN 1 THEN 'IANUARIE'
	WHEN 2 THEN 'FEBRUARIE'
	WHEN 3 THEN 'MARTIE'
	WHEN 4 THEN 'APRILIE'
	WHEN 5 THEN 'MAI'
	WHEN 6 THEN 'IUNIE'
	WHEN 7 THEN 'IULIE'
	WHEN 8 THEN 'AUGUST'
	WHEN 9 THEN 'SEPTEMBRIE'
	WHEN 10 THEN 'OCTOMBRIE'
	WHEN 11 THEN 'NOIEMBRIE'
	WHEN 12 THEN 'DECEMBRIE'
	ELSE '-'
	END
) AS LUNA,
	YEAR(DATA_NASTERII) AS AN
	FROM ANGAJAT