--PROCEDURI (SINTAXA)
CREATE PROCEDURE NUME_PROCEDURA @NUME_PARAM TIP_DATE [=DEFAULT][INPUT/OUTPUT],...
	AS
	INSTRUCTIUNI
	[RETURN] --RETURNUL NUMAI LA MS
	
--EXEMPLU:
--SA SE SCRIE O PROCEDURA CU DREPT DE AFISARE A UNOR CAREVA DATE
ALTER PROCEDURE P1
	AS
	SELECT PRODUCATOR,COUNT(DISTINCT(PC.MODEL_ID)) AS CANTITATE
		FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
		GROUP BY PRODUCATOR

--EXEC ORI EXECUTE NUME_PROCEDURA[VALOARE_PARAMETRU]
EXEC P1

ALTER PROCEDURE P1 @PRET FLOAT=3000,@VITEZA DECIMAL(4,0)=1500
	AS
	SELECT *
		FROM PC WHERE PRET>@PRET AND VITEZA<@VITEZA;

EXEC P1 @VITEZA=6000

--SA SCRIE O PROCEDURA CARE VA AVEA DREPT EFECT CAUTAREA INFORMATIEI DUPA PRET A PRODUSELOR
CREATE FUNCTION TAB_VIR()
	RETURNS TABLE
	AS
	RETURN 
	(
		SELECT 'PC' AS TIP,MODEL_ID,VITEZA,PRET
			FROM PC
			UNION
		SELECT 'LAPTOP',MODEL_ID,VITEZA,PRET
			FROM LAPTOPURI
			UNION
		SELECT 'IMPRIMANTE',MODEL_ID,0,PRET
			FROM IMPRIMANTE
	)

CREATE PROCEDURE P2 @SUMA1 FLOAT=0,@SUMA2 FLOAT=0
	AS
	SELECT *
		FROM DBO.TAB_VIR() WHERE PRET BETWEEN @SUMA1 AND @SUMA2

EXEC P2 @SUMA2=6000

--SA SE SCRIE O PROCEDURA CARE VA CALCULA PRETUL MEDIU AL UNUI ANUMIT TIP DE PRODUS
ALTER PROCEDURE P3 @TIP VARCHAR(250)--,@REZ FLOAT OUTPUT
	AS
	DECLARE @REZ FLOAT;
	IF @TIP='PC'
	BEGIN
		SET @REZ=(SELECT AVG(PRET) FROM PC)	
	END;
	ELSE IF @TIP='LAPTOP'
	BEGIN
		SET @REZ=AVG(PRET) FROM LAPTOPURI
	END;
	ELSE IF @TIP='IMPRIMANTE'
	BEGIN
		SET @REZ=AVG(PRET) FROM IMPRIMANTE
	END;

EXEC P3 @TIP='PC'

--CU PARAMETRU DE IESIRE (OUTPUT)
DECLARE @XXX FLOAT
EXEC P3 @TIP='LAPTOP',@XXX OUTPUT
PRINT 'MEDIA ARITMETICA A '+@TIP+'-ULUI='+CAST(@XXX AS VARCHAR(20));
--SA SE CREEZE O PROCEDURA CARE VA RETURNA VALORILE TABELELOR UNIFICATE
CREATE PROCEDURE P5
	AS
	SELECT 'PC' AS TIP,MODEL_ID,VITEZA,PRET FROM PC
		UNION
	SELECT 'LAPTOP',MODEL_ID,VITEZA,PRET FROM LAPTOPURI
		UNION
	SELECT 'IMPRIMANTE',MODEL_ID,0,PRET FROM IMPRIMANTE

--EFECTUAM INSCRIEREA PROCEDURII CREATE IN TABELA VIRTUALA
CREATE PROCEDURE P6 @TIP VARCHAR(10)
	AS
	CREATE TABLE #MYTABLE(TIP VARCHAR(20),MODEL_ID INT,VITEZA FLOAT,PRET FLOAT)
		INSERT INTO #MYTABLE EXEC P5
		IF @TIP='MAXIM' BEGIN
		SELECT * FROM #MYTABLE
			WHERE PRET=(SELECT MAX(PRET) FROM #MYTABLE)
			END;
		ELSE BEGIN
		SELECT * FROM #MYTABLE
			WHERE PRET=(SELECT MIN(PRET) FROM #MYTABLE)
			END;
EXEC P6 @TIP='MAXIM'