USE DEPO
SELECT *
	FROM PRODUSE,PC
	WHERE PC.MODEL_ID=PRODUSE.MODEL_ID

SELECT *
	FROM PC INNER JOIN PRODUSE P ON P.MODEL_ID=PC.MODEL_ID

SELECT PRODUCATOR,PC.MODEL_ID AS MODEL,PRET
	FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID

SELECT PRODUCATOR,PC.MODEL_ID AS MODEL,PRET
	FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID

SELECT PRODUCATOR,I.MODEL_ID AS MODEL,COLOR
	FROM PRODUSE P INNER JOIN IMPRIMANTE I ON I.MODEL_ID=P.MODEL_ID
	WHERE COLOR='DA'

SELECT PRODUCATOR
	FROM IMPRIMANTE I INNER JOIN PRODUSE P ON P.MODEL_ID=I.MODEL_ID
	WHERE COLOR='NU'

SELECT PRODUCATOR,SUM(PRET) AS COST
	FROM PRODUSE P INNER JOIN PC ON P.MODEL_ID=PC.MODEL_ID
	GROUP BY PRODUCATOR

SELECT P.MODEL_ID,I.TIP,PRODUCATOR
	FROM IMPRIMANTE I INNER JOIN PRODUSE P ON P.MODEL_ID=I.MODEL_ID

SELECT PRODUCATOR,COUNT(*) AS NR
	FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID
	WHERE VITEZA BETWEEN 1500 AND 3000
	GROUP BY PRODUCATOR
	HAVING COUNT(*)>1
