--STUDIUL JOIN
SELECT [NUME_TABEL.]NUME_CAMP
FROM TABEL1,TABEL2,...
WHERE TABELA1.CH_PRIMARA=TABEL2.CH_EXTERNA

USE DEPO
--METODA CLASICA
SELECT * FROM PRODUSE,PC
	WHERE PC.MODEL_ID=PRODUSE.MODEL_ID
--JOIN
--INTERSECTIA DINTRE 2 TABELE
SELECT * FROM PC INNER JOIN PRODUSE ON 
PRODUSE.MODEL_ID=PC.MODEL_ID

--SA SE AFISEZE PRODUCATORII, MODELELE SI PRETUL
SELECT PRODUCATOR,PC.MODEL_ID AS MODEL, PRET
	FROM PRODUSE INNER JOIN PC ON 
	PC.MODEL_ID=PRODUSE.MODEL_ID

--REDENUMIREA TABELELOR(NUMAI LOGIC)
SELECT PRODUCATOR,PC.MODEL_ID AS MODEL, PRET
	FROM PRODUSE P INNER JOIN PC ON 
	PC.MODEL_ID=P.MODEL_ID

--SA SE GASEASCA PRODUCATORII IMPRIMANTELOR COLOR.
SELECT PRODUCATOR,IMPRIMANTE.MODEL_ID AS MODEL,COLOR
	FROM PRODUSE P INNER JOIN IMPRIMANTE ON
	IMPRIMANTE.MODEL_ID=P.MODEL_ID
	WHERE COLOR='DA'
--ALTA
SELECT PRODUCATOR FROM IMPRIMANTE I INNER JOIN
	PRODUSE P ON P.MODEL_ID=I.MODEL_ID WHERE COLOR='NU'

--PENTRU FIECARE PRODUCATOR SA SE CALCULEZE COSTUL
--PRODUSULUI PC
SELECT PRODUCATOR,SUM(PRET) AS COST
	FROM PRODUSE P
	INNER JOIN PC ON
	P.MODEL_ID=PC.MODEL_ID
	GROUP BY PRODUCATOR

--SA SE SCRIE O INTEROGARE CARE AR AFISA
--MODELUL, TIPUL IMPRIMANTEI SI PRODUCATORUL
SELECT P.MODEL_ID,I.TIP,PRODUCATOR 
	FROM IMPRIMANTE I INNER JOIN PRODUSE P ON 
	P.MODEL_ID=I.MODEL_ID

--
SELECT PRODUCATOR,COUNT(*) AS NR
	FROM PRODUSE P INNER JOIN LAPTOPURI L
	ON L.MODEL_ID=P.MODEL_ID 
	WHERE VITEZA BETWEEN 1500 AND 3000
	GROUP BY PRODUCATOR
	HAVING COUNT(*)>1

SELECT * FROM PRODUSE


	