--SINTAXA DE DECLARARE A TABELELOR
CREATE TABLE NUME_TABELA
(
	NUME_CAMP_1 TIP_DATE [CONSTRANGERI]
	...
	NUME_CAMP_N TIP_DATE [CONSTRANGERI]
)

CREATE TABLE PERSOANE
(
	PERSOANE_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20) NOT NULL,
	PRENUME VARCHAR(20) NOT NULL,
	DATA_NASTERII DATE,
	GEN BIT DEFAULT 1,
	DATA_INREGISTRARII DATE DEFAULT GETDATE()
)

CREATE TABLE JOC
(
	JOC_ID INT IDENTITY(1,1),
	NUME VARCHAR(50)
	CONSTRAINT PK_JOC_ID PRIMARY KEY(JOC_ID)
)

CREATE TABLE JOC_PREFERAT
(
	JOC_PREFERAT_ID INT PRIMARY KEY IDENTITY(1,1),
	PERSOANE_ID INT FOREIGN KEY REFERENCES PERSOANE(PERSOANE_ID),
	JOC_ID INT FOREIGN KEY REFERENCES JOC(JOC_ID)
)