USE DEPO

SELECT P.MODEL_ID,I.TIP,PRODUCATOR 
	FROM IMPRIMANTE I INNER JOIN PRODUSE P ON
	I.MODEL_ID=P.MODEL_ID
SELECT PRODUCATOR,COLOR
	FROM IMPRIMANTE INNER JOIN PRODUSE ON
	IMPRIMANTE.MODEL_ID=PRODUSE.MODEL_ID
	WHERE COLOR='DA'
SELECT PRODUCATOR,SUM(PRET) AS PRET
	FROM PC INNER JOIN PRODUSE ON
	PRODUSE.MODEL_ID=PC.MODEL_ID
	GROUP BY PRODUCATOR
SELECT SUM(VITEZA) AS VITEZA,PRODUCATOR
	FROM PC INNER JOIN PRODUSE ON
	PC.MODEL_ID=PRODUSE.MODEL_ID
	GROUP BY PRODUCATOR
SELECT MAX(RAM) AS MAXIM,PRODUCATOR
	FROM PC INNER JOIN PRODUSE P ON
	PC.MODEL_ID=P.MODEL_ID
	GROUP BY PRODUCATOR

	
