CREATE TABLE PERSOANA
(
	PERSOANA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20),
	PRENUME VARCHAR(20),
	DATA_NASTERII DATE,
	GEN BIT DEFAULT 1,
	DATA_INREGISTRARII DATE DEFAULT GETDATE()
)

INSERT INTO PERSOANA(NUME,PRENUME)
	VALUES('POPOV','ION')

INSERT INTO PERSOANA(NUME,PRENUME,DATA_NASTERII,GEN)
	VALUES('MANDALAC','','1990-01-05',0)

SET IDENTITY_INSERT PERSOANA ON
INSERT INTO PERSOANA(PERSOANA_ID,NUME,PRENUME,DATA_NASTERII,GEN)
	VALUES(100,'BURUIANA','ALEXA',NULL,0)

SET IDENTITY_INSERT PERSOANA OFF
INSERT INTO PERSOANA(NUME,PRENUME,DATA_NASTERII,GEN)
	VALUES('BURUIANA','PETRU','2000-01-08,1',1)

DELETE NUME_TABELA WHERE [CONDITIE]

DELETE PERSOANA WHERE PERSOANA_ID=100