CREATE DATABASE TEST

USE TEST

CREATE TABLE PERSOANA (
	PERSOANA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(50) NOT NULL,
	PRENUME VARCHAR(50),
	DATA_NASTERII DATE,
	GEN BIT DEFAULT 1,
	DATA_INREGISTRARII DATE DEFAULT GETDATE()
)

INSERT INTO PERSOANA(NUME,PRENUME)
	VALUES('POPOV','ION')

INSERT INTO PERSOANA(NUME,PRENUME,DATA_NASTERII,GEN)
	VALUES('MANDALAC','','1990-01-05',0)

SET IDENTITY_INSERT PERSOANA ON --SET - INSEAMANA A SETA
INSERT INTO PERSOANA(PERSOANA_ID,NUME,PRENUME,DATA_NASTERII,GEN)
	VALUES(100,'BURUIANA','ALEXA',NULL,0)

SET IDENTITY_INSERT PERSOANA OFF
INSERT INTO PERSOANA(NUME,PRENUME,DATA_NASTERII,GEN)
	VALUES('BURUIANA','PETRU','2000-01-08',1)

--------ELIMINAREA DATELOR-----------------
DELETE NUME_TABELA WHERE [CONDITIE]

DELETE PERSOANA WHERE PERSOANA_ID=100