SELECT IMPRIMANTA_ID,COLOR,TIP,PRET
	FROM IMPRIMANTE

SELECT LAPTOP_ID,VITEZA,ECRAN,PRET
	FROM LAPTOPURI

SELECT PC_ID,VITEZA,HDD,RAM,PRET
	FROM PC

SELECT MODEL_ID,PRODUCATOR,TIP,ACTIV
	FROM PRODUSE

SELECT * FROM PC

SELECT *,HDD+HDD AS 'SUMA_HDD',ECRAN,PRET
	FROM LAPTOPURI

SELECT *, VITEZA+VITEZA AS 'SUMA_VITEZA_PC',RAM,CD
	FROM PC

SELECT RAM+RAM AS 'SUMA_RAM_PC',CD,HDD,PRET
	FROM PC

SELECT PC_ID,RAM,RAM+RAM AS 'SUMA_RAM_PC',CD,HDD,PRET
	FROM PC

SELECT IMPRIMANTA_ID,COLOR,PRET+PRET AS 'SUMA PRET'
	FROM IMPRIMANTE