USE DEPO

SELECT *,CONCAT(TIP,5,TIP) AS CONCATINARE,
	'5'+TIP AS CONCATE,
	5+5 AS SUMA,
	'5'+'5' AS SUMA2
	FROM PRODUSE

SELECT *,SUBSTRING(TIP,1,1) AS SUBSIR
	FROM PRODUSE

SELECT *,SUBSTRING(TIP,3,3) AS SUBSIR
	FROM PRODUSE

SELECT *,LEN(TIP)
	FROM PRODUSE

SELECT *,SUBSTRING(TIP,LEN(TIP),1)
	FROM PRODUSE

SELECT *,LOWER(TIP),
	UPPER(LOWER(TIP))
	FROM PRODUSE

SELECT *,CONCAT(UPPER(SUBSTRING(TIP,1,1)),
	SUBSTRING(LOWER(TIP),2,LEN(TIP)-2),
	UPPER(SUBSTRING(TIP,LEN(TIP),1)))
	FROM IMPRIMANTE