SELECT NUME+' '+PRENUME AS NUME,DATA_NASTERII,
	(
		SELECT DATA_ANGAJARII FROM ANGAJARE A INNER JOIN ANGAJAT AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID,
		(
			CASE
			WHEN CAST(YEAR(DATA_NASTERII) AS INT)<CAST(YEAR(DATA_ANGAJARII) AS INT)
			THEN CAST(YEAR(DATA_ANGAJARII)AS INT)-CAST(YEAR(DATA_NASTERII) AS INT)
			ELSE 'NU EXISTA'
			END
		)
	) AS AN
	FROM ANGAJAT

--IMI SCRIE CA 'INCORRECT SYNTAX NEAR KEYWORD 'CASE' '