/* ORDER BY IS ALWAYS SET TO BE ASC - ASCENDING */
SELECT * FROM PRODUCTS ORDER BY ID;

SELECT * FROM PRODUCTS ORDER BY ID DESC;

SELECT NAME FROM PRODUCTS;

SELECT NAME AS NAME_PRODUCT, IS_SALE AS SALE FROM PRODUCTS;

SELECT * FROM PRODUCTS WHERE ID = 10;

SELECT * FROM PRODUCTS WHERE INVENTORY = 5;

SELECT * FROM PRODUCTS WHERE INVENTORY > 25 AND INVENTORY < 70;

SELECT * FROM PRODUCTS WHERE ID = 1 OR ID = 2;

SELECT * FROM PRODUCTS WHERE ID IN(1, 2, 3);

SELECT * FROM PRODUCTS WHERE NAME LIKE 'TV%';

SELECT * FROM PRODUCTS WHERE NAME LIKE '%b%' OR NAME LIKE '%B%';

SELECT * FROM PRODUCTS WHERE NAME LIKE '%b%';

SELECT * FROM PRODUCTS;

SELECT * FROM PRODUCTS LIMIT 7;

