INSERT INTO PRODUCTS (NAME, PRICE, INVENTORY) VALUES('SOFT TOY', 15, 20) RETURNING *;

/* 'RETURNING (COLUMNS)' RETURNS THE DATA WITH THE FIELDS WE WOULD PREFER  */

SELECT * FROM PRODUCTS;

DELETE FROM PRODUCTS WHERE ID = 18 RETURNING *;

DELETE FROM PRODUCTS WHERE INVENTORY = 0;

UPDATE PRODUCTS SET NAME = 'BIG TOY CAR' WHERE ID = 17; 