SELECT * FROM PRODUCTS ORDER BY ID ASC;

SELECT NAME FROM PRODUCTS;

SELECT ID, NAME, PRICE FROM PRODUCTS;

SELECT ID AS PRODUCT_ID, NAME AS PRODUCT_NAME, PRICE AS PRODUCT_PRICE FROM PRODUCTS;

SELECT * FROM PRODUCTS WHERE ID = 1;

SELECT * FROM PRODUCTS WHERE INVENTORY > 5;

SELECT * FROM PRODUCTS WHERE INVENTORY != 5;

SELECT * FROM PRODUCTS WHERE INVENTORY > 10 AND PRICE > 50;

SELECT * FROM PRODUCTS WHERE ID IN (1, 2, 3);

SELECT * FROM PRODUCTS WHERE NAME LIKE 'TV%'; /* EVERYTHING THAT HAS TV */

SELECT * FROM PRODUCTS WHERE NAME LIKE 'R%'; /* EVERYTHING THAT HAS r */

SELECT * FROM PRODUCTS ORDER BY PRICE DESC;

SELECT * FROM PRODUCTS ORDER BY INVENTORY ASC, PRICE DESC;

SELECT * FROM PRODUCTS ORDER BY CREATED_AT;

SELECT * FROM PRODUCTS ORDER BY ID LIMIT 7 OFFSET 2; /* OFFSET IS SKIPPING THE FIRST 2 ROWS */

INSERT INTO PRODUCTS(name, price, inventory) VALUES('Banana', 2, 150), ('Apple', 1, 200);

INSERT INTO PRODUCTS(NAME, PRICE) VALUES ('CAR', 15000) RETURNING *;

DELETE FROM PRODUCTS WHERE ID = 20;

DELETE FROM PRODUCTS WHERE ID = 19 RETURNING *;

DELETE FROM PRODUCTS WHERE INVENTORY = 0 RETURNING *;

UPDATE PRODUCTS SET NAME = 'TV STATION', PRICE = 150 WHERE ID = 1 RETURNING *;

UPDATE PRODUCTs SET IS_SALE = true;


