USE DEPO
SELECT SUM(PRET) AS SUMA_VIT,
	AVG(PRET),
	SUM(PRET)/COUNT(*),
	MIN(PRET),
	MAX(PRET)
	FROM LAPTOPURI

SELECT DISTINCT(PRODUCATOR),TIP
	FROM PRODUSE

SELECT PRODUCATOR,TIP
	FROM PRODUSE

SELECT PRODUCATOR,TIP
	FROM PRODUSE GROUP BY PRODUCATOR,TIP

SELECT PRODUCATOR,COUNT(*) AS NR
	FROM PRODUSE
	GROUP BY PRODUCATOR

SELECT COLOR,COUNT(*) AS NUMAR,SUM(PRET) AS SUMA_PRET
	FROM IMPRIMANTE
	GROUP BY COLOR

SELECT TIP,COUNT(*) AS NUMAR1,SUM(PRET) AS SUMA1_PRET
	FROM IMRPRIMANTE
	GROUP BY TIP

SELECT * FROM PC
SELECT MODEL_ID,SUM(PRET) AS SUMA
	FROM PC
	GROUP BY MODEL_ID HAVING SUM(PRET)>=3000

SELECT *
	FROM PC
	WHERE VITEZA>3000

SELECT *
	FROM PC
	WHERE HDD!=500

SELECT *
	FROM PC
	WHERE VITEZA>=2000 AND VITEZA<=3000

SELECT *
	FROM PC
	WHERE VITEZA BETWEEN 2000 AND 3000

SELECT *
	FROM PC
	WHERE CD='12X' OR CD='24X'

SELECT *
	FROM PC
	WHERE CD IN('12X','24X')

SELECT *
	FROM LAPTOPURI
	WHERE ECRAN>=13 AND HDD>=500

SELECT *
	FROM PC WHERE PRET<=8000 AND HDD BETWEEN 500 AND 1000

SELECT *
	FROM PC
	WHERE VITEZA BETWEEN 2000 AND 4000 AND (CD='24X' OR CD='40X' OR CD='52X')

SELECT *
	FROM PC
	WHERE VITEZA BETWEEN 2000 AND 4000 AND CD NOT IN('24X','40X','52X')