USE DEPO
SELECT *,CONCAT(HDD,HDD) AS HARD_DISK
	FROM PC

SELECT *,SUBSTRING(TIP,1,2) AS MODEL_MOD
	FROM PRODUSE

SELECT *,LEN(TIP)
	FROM PRODUSE

SELECT *,LOWER(TIP)
	FROM PRODUSE

SELECT SUM(VITEZA)
	FROM LAPTOPURI

SELECT AVG(PRET)
	FROM LAPTOPURI

SELECT HDD,CAST(SUBSTRING(CAST(HDD AS VARCHAR(4)),1,1) AS INT)+
	CAST(SUBSTRING(CAST(HDD AS VARCHAR(4)),2,1) AS INT)+
	CAST(SUBSTRING(CAST(HDD AS VARCHAR(4)),3,1) AS INT)+
	CAST(SUBSTRING(CAST(HDD AS VARCHAR(4)),4,1) AS INT) AS SUMA_HDD
	FROM PC

SELECT MAX(HDD) AS MAX_HDD
	FROM PC

SELECT *,
	CONCAT(UPPER(SUBSTRING(TIP,1,1)),
	SUBSTRING(LOWER(TIP),2,LEN(TIP)-1)) AS TIP_FRUMOS
	FROM IMPRIMANTE