SP_HELPTRIGGER PRODUSE

ENABLE TRIGGER LG ON PRODUSE

UPDATE PC SET PRET=6900
	WHERE PC_ID=14

CREATE TABLE MENTENANTA
(
	LOG_ID INT PRIMARY KEY IDENTITY(1,1),
	PROCES VARCHAR(30),
	STATUT VARCHAR(30),
	DATA_EXEC DATE DEFAULT GETDATE(),
	ORA_EXEC TIME DEFAULT GETDATE()
)

INSERT INTO ANGAJAT.DBO.MENTENANTA(STATUT,PROCES)
	VALUES('SUCCES','CLEANUP TASK')

SELECT * FROM ANGAJAT.DBO.MENTENANTA

ALTER TABLE MENTENANTA ADD BACKUPP INT DEFAULT 0

CREATE TRIGGER M_LG ON MENTENANTA
	AFTER INSERT,UPDATE
	AS
	DECLARE @TIP INT;
	DECLARE @MESS VARCHAR(200);
	IF UPDATE(BACKUPP)
	BEGIN
		SET @TIP=(SELECT BACKUPP FROM inserted)
		IF(@TIP=1) SET @MESS='BACKUP SUCCES'
		ELSE SET @MESS='BACKUP FAILURE'
	END;
	EXEC MSDB.DBO.SP_SEND_DBMAIL
	@PROFILE_NAME='MCCMAIL',
	@RECIPIENTS='mr.marius05@mail.ru',
	@BODY=@MESS,
	@SUBJECT='BACKUP ANGAJAT'
