USE ANGAJAT
CREATE TABLE LOCALITATE (
	LOCALITATE_ID INT PRIMARY KEY IDENTITY(1,1),
	RAION_ID INT FOREIGN KEY REFERENCES RAION(RAION_ID),
	NUME VARCHAR(30)
)

DROP TABLE LOCALITATE

CREATE TABLE STRADA (
	STRADA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(50) NOT NULL
)

CREATE TABLE STR_LOC (
	STR_LOC_ID INT PRIMARY KEY IDENTITY(1,1),
	STRADA_ID INT FOREIGN KEY REFERENCES STRADA(STRADA_ID),
	LOCALITATE_ID INT FOREIGN KEY REFERENCES LOCALITATE(LOCALITATE_ID)
)

CREATE TABLE PERSOANA (
	PERSOANA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20) NOT NULL,
	PRENUME VARCHAR(20)	NOT NULL,
	DATA_NAST DATE NOT NULL,
	GEN CHAR,
	STR_LOC_ID INT FOREIGN KEY REFERENCES STR_LOC(STR_LOC_ID),
	NR VARCHAR(10),
	BL VARCHAR(10),
	AP VARCHAR(10),
)

CREATE TABLE DEPARTAMENT (
	DEPARTAMENT_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(50)
)

CREATE TABLE FUNCTIA (
	FUNCTIA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(20)
)

CREATE TABLE ANGAJARE (
	ANGAJARE_ID INT PRIMARY KEY IDENTITY(1,1),
	PERSOANA_ID INT FOREIGN KEY REFERENCES PERSOANA(PERSOANA_ID),
	FUNCTIA_ID INT FOREIGN KEY REFERENCES FUNCTIA(FUNCTIA_ID),
	DEPARTAMENT_ID INT FOREIGN KEY REFERENCES DEPARTAMENT(DEPARTAMENT_ID),
	SALARIUL NUMERIC(8,2),
	CCONTRACT VARCHAR(20) NOT NULL
)