USE DEPO

SELECT MODEL_ID,PRODUCATOR,TIP 
	FROM PRODUSE

SELECT *,RAM+RAM AS SUMA_RAM,HDD
	FROM PC

SELECT *,RAM+RAM AS 'SUMA RAM',RAM,HDD
	FROM PC

SELECT *, RAM+RAM SUMA_RAM,RAM,HDD
	FROM PC

SELECT *,PRET*0.2 AS REDUCERE,PRET-(PRET*0.2) AS PRETFIN
	FROM PC