CREATE FUNCTION S(@A_ID INT)
	RETURNS INT
	BEGIN
		DECLARE @R INT;
		SET @R=
		(
			SELECT SUBSTRING(SALARIU,1,1)*SUBSTRING(SALARIU,2,1) AS PRODUS,
				(
					SELECT IIF(SUBSTRING(SALARIU,1,1)*SUBSTRING(SALARIU,2,1)>5,SUBSTRING(SALARIU,LEN(SALARIU),1)*SUBSTRING(SALARIU,LEN(SALARIU)-1,1),0)
						FROM ANGAJARE AA INNER JOIN ANGAJAT A ON AA.ANGAJAT_ID=A.ANGAJAT_ID
				) X
				FROM ANGAJARE AA INNER JOIN ANGAJAT A ON AA.ANGAJAT_ID=A.ANGAJAT_ID	
		);
		RETURN @R;
	END;

--IMI DA EROARE LA SINTAXA, DAR POSIBIL CODUL NU LAM SCRIS CORECT

