CREATE TABLE DISCOUNT
(
	DISCOUNT_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(40),
	VALOAREA INT,
	ACTIV BIT DEFAULT 1
)
CREATE TABLE CLIENT
(
	CLIENT_ID INT PRIMARY KEY IDENTITY(1,1),
	DISCOUNT_ID INT FOREIGN KEY REFERENCES DISCOUNT(DISCOUNT_ID),
	NUME VARCHAR(30),
	PRENUME VARCHAR(30),
	DATA_NAST DATE,
	DATA_REG DATE,
	COD_CLIENT INT	
)
CREATE TABLE FIRMA
(
	FIRMA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(30),
	COD_FISCAL INT,
	ADRESA VARCHAR(60)
)
CREATE TABLE OPERATOR
(
	OPERATOR_ID INT PRIMARY KEY IDENTITY(1,1),
	FIRMA_ID INT FOREIGN KEY REFERENCES FIRMA(FIRMA_ID),
	NUME VARCHAR(30),
	PRENUME VARCHAR(30),
	FUNCTIA VARCHAR(30),
	USERNAME VARCHAR(30),
	PASS VARCHAR(30),
	COD INT,
	TIP_ACCES INT
)
CREATE TABLE CEC
(
	CEC_ID INT PRIMARY KEY IDENTITY(1,1),
	OPERATOR_ID INT FOREIGN KEY REFERENCES OPERATOR(OPERATOR_ID),
	CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
	FIRMA_ID INT FOREIGN KEY REFERENCES FIRMA(FIRMA_ID),
	NR_CEC INT,
	DATA_CEC DATE,
	SUMA_CEC DECIMAL(9,2)
)
CREATE TABLE FACTURA_REC
(
	FACTURA_REC_ID INT PRIMARY KEY IDENTITY(1,1),
	NR_FACTURA INT,
	DATA_FACTURA DATE,
	EMITENT VARCHAR(20)
)
CREATE TABLE UNIT_MASURA
(
	UNIT_MASURA_ID INT PRIMARY KEY IDENTITY(1,1),
	ABREVIERE VARCHAR(30),
	NUME VARCHAR(30)
)
CREATE TABLE PRODUSE
(
	PRODUSE_ID INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE VARCHAR(40),
	COD_PRODUS INT
)
CREATE TABLE RECEPTIE
(
	RECEPTIE_ID INT PRIMARY KEY IDENTITY(1,1),
	PRODUSE_ID INT FOREIGN KEY REFERENCES PRODUSE(PRODUSE_ID),
	UNIT_MASURA_ID INT FOREIGN KEY REFERENCES UNIT_MASURA(UNIT_MASURA_ID),
	FACTURA_REC_ID INT FOREIGN KEY REFERENCES FACTURA_REC(FACTURA_REC_ID),
	OPERATOR_ID INT FOREIGN KEY REFERENCES OPERATOR(OPERATOR_ID),
	STOCK1 FLOAT,
	STOCK2 FLOAT,
	PRET_INTRARE DECIMAL(9,2),
	PRET_VANZARE DECIMAL(9,2)
)
CREATE TABLE VANZARE
(
	VANZARE_ID INT PRIMARY KEY IDENTITY(1,1),
	CEC_ID INT FOREIGN KEY REFERENCES CEC(CEC_ID),
	RECEPTIE_ID INT FOREIGN KEY REFERENCES RECEPTIE(RECEPTIE_ID),
	CANTITATE FLOAT,
	SUMA DECIMAL(9,2),
	SUMA_DISC DECIMAL(9,2),
	SUMA_TOTAL DECIMAL(9,2)
)

INSERT INTO FIRMA(NUME,COD_FISCAL,ADRESA)
	VALUES('BUCURIA','7123888906754','OR.CHISINAU, STR. MIHAI VITEAZU'),
	('TRISTETE','3456172839012','OR.CHISINAU, STR. MIHAI EMINESCU')

INSERT INTO OPERATOR(FIRMA_ID,NUME,PRENUME,FUNCTIA,USERNAME,PASS,COD,TIP_ACCES)
	VALUES(2,'CEBAN','ION','CASIER','CEBANION13','1',' ',1),
	(1,'RUSU','VADIM','CASIER','VADIMRUSU1','2',' ',1),
	(1,'ISAC','VALERIA','DEPOZITAR','VALERIAISAC','3',' ',2),
	(2,'MARZAC','AFANASIE','DEPOZITAR','AFANASIE12','4',' ',2),
	(1,'CEBOTARI','ELENA','CASIER','CEBOTARI3','5',' ',1),
	(2,'MARDARI','EMILIA','DEPOZITAR','MARDARI12','6',' ',2),
	(2,'URSACHI','DUMITRU','ADMINISTRATOR','URSACHI123','7',' ',3),
	(1,'LUPU','DANIEL','ADMINISTRATOR','LUPUD123','8',' ',3)

INSERT INTO UNIT_MASURA(ABREVIERE,NUME)
	VALUES('KG','KILOGRAM'),
	('L','LITRI'),
	('G','GRAME'),
	('BUC','BUCATI')

INSERT INTO PRODUSE(DENUMIRE,COD_PRODUS)
	VALUES('SALAM-MOLDOVENESC',111),
	('LAPTE',222),
	('GRAUNCIOR',333),
	('APA-OM',444),
	('BISCUITI',555),
	('ZEFIR',666),
	('BOMBOANE-BUCUREL',777),
	('VIN SPUMANT',888),
	('SUC-NATURALIS',999),
	('BANANE',000),
	('CAPSUNE',112),
	('ROSII',113),
	('CASTRAVETI',114),
	('BRANZA',115),
	('IAURT DE CAPSUNE',116),
	('IAURT DE BANANE',117),
	('ACTIVIA',118),
	('SMANTANA',119),
	('PAINE ALBA',120),
	('PAINE NEAGRA',121),
	('PAINE SURA',122),
	('LAMAIE',123),
	('MUSTAR',124),
	('KETCHUP',125)
