USE DEPO

SELECT * FROM
(
	SELECT PRODUCATOR,PRET,TIP FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
	UNION ALL
	SELECT PRODUCATOR,PRET,TIP FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID
) ITEMS
WHERE PRET=(SELECT MAX(PRET) FROM (
	SELECT PRODUCATOR,PRET,TIP FROM PRODUSE P INNER JOIN PC ON PC.MODEL_ID=P.MODEL_ID
	UNION ALL
	SELECT PRODUCATOR,PRET,TIP FROM PRODUSE P INNER JOIN LAPTOPURI L ON L.MODEL_ID=P.MODEL_ID	
) MAXIM )

SELECT HDD, COUNT(*) AS NR
	FROM PC
	GROUP BY HDD
	HAVING COUNT(*)>1

USE ANGAJAT

SELECT DENUMIRE,DEPARTAMENT_ID,
(
	SELECT COUNT(DISTINCT(ANGAJAT_ID)) FROM ANGAJARE A WHERE A.DEPARTAMENT_ID=D.DEPARTAMENT_ID
	AND DATA_ELIBARARII IS NULL
) PERSON_ANG,
(
	SELECT COUNT(DISTINCT(ANGAJAT_ID)) FROM ANGAJARE A WHERE A.DEPARTAMENT_ID=D.DEPARTAMENT_ID
	AND DATA_ELIBARARII IS NOT NULL
) PERS_ELIB,
(
	SELECT SUM(SALARIU+BONUS_SALARIU-PENALITATI_SALARIU) FROM ANGAJARE A WHERE A.DEPARTAMENT_ID=D.DEPARTAMENT_ID
	AND DATA_ELIBARARII IS NULL
) SUMA
	FROM DEPARTAMENT D

SELECT
(
	SELECT TOP 1 NUME+' '+PRENUME FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	WHERE AA.SALARIU=(SELECT MAX(SALARIU) FROM ANGAJARE)
) BINE_PLATIT,
(
	SELECT TOP 1 NUME+' '+PRENUME FROM ANGAJAT A INNER JOIN ANGAJARE AA ON AA.ANGAJAT_ID=A.ANGAJAT_ID
	WHERE AA.SALARIU=(SELECT MIN(SALARIU) FROM ANGAJARE)
) PROST_PLATIT

SELECT NUME,PRENUME,SALRIU FROM ANGAJAT A INNER JOIN ANGAJARE AA ON A.ANGAJAT_ID=AA.ANGAJAT_ID
WHERE SALARIU=(SELECT MIN(SALARIU) FROM ANGAJARE) OR SALARIU=(SELECT MAX(SALARIU) FROM ANGAJARE)